# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler
  labels:
    app: autoscaler
spec:
  selector:
    matchLabels:
      app: autoscaler
  replicas: 1
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      containers:
      - name: autoscaler
        image: woodpeckerci/autoscaler:next
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        env:
        - name: WOODPECKER_SERVER
          value: https://woodpecker.ramona.fun/
        - name: WOODPECKER_MIN_AGENTS
          value: "0"
        - name: WOODPECKER_MAX_AGENTS
          value: "1"
        - name: WOODPECKER_WORKFLOWS_PER_AGENT
          value: "2"
        - name: WOODPECKER_GRPC_ADDR
          value: "woodpecker-grpc.ramona.fun"
        - name: WOODPECKER_GRPC_SECURE
          value: "true"
        - name: WOODPECKER_PROVIDER
          value: "scaleway"
        - name: WOODPECKER_SCALEWAY_SERVER_TYPES 
          value: "GP1-XS:nl-ams-1"
        - name: WOODPECKER_SCALEWAY_PROJECT
          value: "ed770f01-66c8-4181-8fc7-6821ef6cac9a"
        - name: WOODPECKER_SCALEWAY_TAGS
          value: "woodpecker,ci"
        - name: WOODPECKER_SCALEWAY_STORAGE_TYPE
          value: "sbs_volume"
        - name: WOODPECKER_CLOUDINIT_TEMPLATE
          valueFrom:
            secretKeyRef:
              name: autoscaler-userdata
              key: userdata
        envFrom:
          - secretRef:
              name: autoscaler
      restartPolicy: Always
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autoscaler
spec:
  refreshInterval: 1m
  target:
    name: autoscaler
    creationPolicy: Owner
    template:
      data:
        WOODPECKER_TOKEN: "{{ .WOODPECKER_TOKEN }}"
        WOODPECKER_SCALEWAY_ACCESS_KEY: "{{ .WOODPECKER_SCALEWAY_ACCESS_KEY }}"
        WOODPECKER_SCALEWAY_SECRET_KEY: "{{ .WOODPECKER_SCALEWAY_SECRET_KEY }}"
  dataFrom:
    - sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault
      extract:
        key: woodpecker/autoscaler
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autoscaler-userdata
spec:
  refreshInterval: 1m
  target:
    name: autoscaler-userdata
    creationPolicy: Owner
    template:
      data:
        userdata: |-
          {{`#cloud-config

          package_reboot_if_required: false
          package_update: true
          package_upgrade: false

          groups:
            - docker

          system_info:
            default_user:
              groups: [ docker ]

          apt:
            sources:
              docker.list:
                keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
                keyserver: https://download.docker.com/linux/ubuntu/gpg
                source: deb [signed-by=$KEY_FILE] https://download.docker.com/linux/ubuntu $RELEASE stable

          packages:
            - docker-ce
            - docker-compose-plugin
            - binfmt-support
            - qemu-user-static

          write_files:
          - path: /root/docker-compose.yml
            content: |
              # docker-compose.yml
              version: '3'
              services:
                woodpecker-agent:
                  image: {{ .Image }}
                  restart: always
                  volumes:
                    - /var/run/docker.sock:/var/run/docker.sock
                  environment:
                    {{- range $key, $value := .Environment }}
                    - {{ $key }}={{ $value }}
                    {{- end }}

          runcmd:
            {{- range .PreExec }}
            - {{ . }}
            {{- end }}`}}
            - ['sh', '-c', 'curl -fsSL https://tailscale.com/install.sh | sh']
            - ['sudo', 'tailscale', 'up', '--auth-key={{ .authkey }}']
            {{`
            - sh -xc "cd /root; docker compose up -d"
            {{- range .PostExec }}
            - {{ . }}
            {{- end }}
            `}}

          final_message: "The system is finally up, after $UPTIME seconds"
  dataFrom:
    - sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault
      extract:
        key: woodpecker/userdata
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
