apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: woodpecker
spec:
  parentRefs:
  - name: gateway-public
    kind: Gateway
    namespace: kgateway-system
    group: gateway.networking.k8s.io
  hostnames:
    - woodpecker.ramona.fun
  rules:
    - backendRefs:
      - name: woodpecker-server
        kind: Service
        port: 80
        group: ""
        weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
      timeouts:
        backendRequest: "1800s"
        request: "1800s"
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: grpc
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway-public
      namespace: kgateway-system
  hostnames:
    - woodpecker-grpc.ramona.fun
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: woodpecker-server
          weight: 1
          port: 9000
