apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: woodpecker
    repo: oci://ghcr.io/woodpecker-ci/helm/
    releaseName: woodpecker
    version: "3.7.0"
    namespace: woodpecker
    valuesInline:
      agent:
        env:
          WOODPECKER_BACKEND_K8S_PULL_SECRET_NAMES: 'ghcr'
      server:
        prometheus:
          podmonitor:
            enabled: true
          rules:
            enabled: true
        grafana:
          dashboards:
            enabled: true
        env:
          WOODPECKER_HOST: 'https://woodpecker.ramona.fun'
          WOODPECKER_OPEN: 'true'
          WOODPECKER_ADMIN: 'ramona'
          WOODPECKER_FORGEJO: 'true'
          WOODPECKER_FORGEJO_URL: 'https://code.ramona.fun'
          WOODPECKER_DATABASE_DRIVER: postgres
        extraSecretNamesForEnvFrom: ["woodpecker-secrets", "woodpecker-db"]
resources:
  - http-route.yaml
  - secret.yaml
  - database.yaml
