apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: agent-secret
spec:
  deletionPolicy: Delete
  refreshInterval: 1m
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: woodpecker-default-agent-secret
  data:
    - match:
        remoteRef:
          remoteKey: woodpecker/agent-secret
      conversionStrategy: None
