apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-secrets
spec:
  refreshInterval: 1m
  target:
    name: woodpecker-secrets
    creationPolicy: Owner
    template:
      data:
        WOODPECKER_FORGEJO_CLIENT: '{{ .client }}'
        WOODPECKER_FORGEJO_SECRET: '{{ .secret }}'
  dataFrom:
    - sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault
      extract:
        key: woodpecker/secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
