apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  attic.conf: |-
    listen = "0.0.0.0:8080"
    allowed-hosts = ["attic.infrastructure.ramona.fun"]
    api-endpoint = "https://attic.infrastructure.ramona.fun/"
    
    [storage]
    type = "s3"
    bucket = "attic"
    region = "us-east-1"
    endpoint = "https://s3.us-west-002.backblazeb2.com"
    
    [database]
    [chunking]
    nar-size-threshold = 65536 # chunk files that are 64 KiB or larger
    min-size = 16384
    avg-size = 65536
    max-size = 262144
