apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  attic.conf: |-
    listen = "0.0.0.0:8080"
    allowed-hosts = ["attic.infrastructure.ramona.fun"]
    api-endpoint = "https://attic.infrastructure.ramona.fun/"
    
    [storage]
    type = "s3"
    bucket = "ramona-attic"
    region = "nbg1"
    endpoint = "https://nbg1.your-objectstorage.com/"
    
    [database]
    [chunking]
    nar-size-threshold = 262144 # chunk files that are 64 KiB or larger
    min-size = 262144
    avg-size = 524288
    max-size = 1048576
