apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  attic.conf: -|
    listen = "0.0.0.0:8080"
    allowed-hosts = ["attic.infrastructure.ramona.fun"]
    api-endpoint = "https://attic.infrastructure.ramona.fun"
    
    [storage]
    type = "s3"
    bucket = "attic"
    endpoint = "https://rustfs.infrastructure.ramona.fun"
