apiVersion: apps/v1
kind: Deployment
metadata:
  name: attic
  labels:
    app: attic
spec:
  selector:
    matchLabels:
      app: attic
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: attic
    spec:
      imagePullSecrets:
        - name: forgejo-container-credentials
      containers:
        - name: attic
          image: code.ramona.fun/ramona/monorepo/attic:1786960918.194204
          imagePullPolicy: IfNotPresent
          command:
            - /bin/atticd
            - --config
            - /etc/attic/attic.conf
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 2Gi
          volumeMounts:
            - mountPath: /etc/attic/
              name: config
            - mountPath: /var/data/
              name: data
          envFrom:
            - secretRef:
                name: attic
            - secretRef:
                name: db
          ports:
            - containerPort: 8080
              name: attic
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: config
          configMap:
            name: config
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db
spec:
  refreshInterval: 1m
  target:
    name: db
    creationPolicy: Owner
    template:
      data:
        ATTIC_SERVER_DATABASE_URL: 'postgres://{{ .username }}:{{ .password }}@cloudnative-pg-database-cluster-pooler-rw.cloudnative-pg-database/attic'
  dataFrom:
    - sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault
      extract:
        key: postgres/attic
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: attic
spec:
  refreshInterval: 1m
  target:
    name: attic
    creationPolicy: Owner
    template:
      data:
        ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64: '{{ .ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64 }}'
  dataFrom:
    - sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault
      extract:
        key: attic/secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-container-credentials
spec:
  target:
    name: forgejo-container-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ index . "docker-config-json" | toString }}'
  dataFrom:
    - sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault
      extract:
        key: forgejo-container-registry-config
