apiVersion: apps/v1
kind: Deployment
metadata:
  name: attic
  labels:
    app: attic
spec:
  selector:
    matchLabels:
      app: attic
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: attic
    spec:
      containers:
        - name: attic
          image: ghcr.io/ramonacat/attic:1784761083
          imagePullPolicy: IfNotPresent
          command:
            - /bin/atticd
            - --config
            - /etc/attic/attic.conf
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 2Gi
          volumeMounts:
            - mountPath: /etc/attic/
              name: config
          envFrom:
            - secretRef:
                name: attic
            - secretRef:
                name: db
          ports:
            - containerPort: 8080
              name: attic
      volumes:
        - name: config
          configMap:
            name: config
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db
spec:
  refreshInterval: 1m
  target:
    name: db
    creationPolicy: Owner
    template:
      data:
        ATTIC_SERVER_DATABASE_URL: 'postgres://{{ .username }}:{{ .password }}@cloudnative-pg-database-cluster-pooler-rw.cloudnative-pg-database/attic'
  dataFrom:
    - sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault
      extract:
        key: postgres/attic
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: attic
spec:
  refreshInterval: 1m
  target:
    name: attic
    creationPolicy: Owner
    template:
      data:
        ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64: '{{ .ATTIC_SERVER_TOKEN_RS256_SECRET_BASE64 }}'
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault
      extract:
        key: attic/secret
