---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdesc
  namespace: cloudnative-pg-database
spec:
  encryptedData:
    password: AgAX7nUuG+Vzc/0vfB3LNzZESdPdxj3Z02F0V7dlt+y7lWFIm2+B6YAa/qe/D0liQJQRF20iAr22qv7EChTVzwah0cx2Sbr9ZKXY6RAgWwCksjX1QdPsx4YHMdAg4sWU4XgeRu6G0koEwkaAgNgFw/HgNQM+oxwiGWlW4ou03HA53vQmAPhwCKGgB/MvoQfZHpVPF7t/5xu7uU1xN+phJzvRVuPKH8i7JMe5XOzkh+kX23+GOW5xn+smx35kH8xVzPoZ/B25OkWvoZ0jwX9cfKba9MgBojIsAZYeBS5Ug4bBakvdf8YmAoUPAyVQKV/bPOFtSpkxlNA4CBvYgSFE4elbeGpOuFGFNinH62LpmDQAPbkDmJNdzj4o4QCefX25YEnB7zpY3/9OaqkeOi1kP2MYG3SPqSr8czMLyQLNJDtJ7I0N/9Aw/6sYKnPDzLuxn1ZYOwXeAXK9S85PdyAedesmo+My94PX1E9awYNrlin5BHMcmPfixt8nMp5awmFu+N5ucyHj+ZDtbX7kZr3h7SmznufsVKx+sYirCq2O3sFHsK9/qBGlncyJO0fy5QqeHvvvSIS46Na9dXcMA3SOl0Kxlq9kE2LlqltoXtxb43AYpzV4eKVH21a3ak0zhmNDJsFarTyyBDcMfPiS6tHHg6qG+NjtGK0x/PVfmkl8dwpmVplxwX0tXvKQ+ouxGuwj9QGB0/4JIX/NByx0
    username: AgCmAZZsxTW45d/uVRy159BCsEeJlLHuLtS8cU/BIjv+saCkBoEg10lj4dcxJtDqbnPWWBldS3sG56b1eeglUAtkBJkSbccMxeB7uMH89vg/HHIq3CCfIzkBv2Gyn40Z2lNymG7zelBqvpjmEjhoThesfnut1cR4McGuKv0SzINtcGzGYXsyHe0rkmrU7EBN3dyLxSqVZvAbLxKcrvB+GEPxuaIWLeCgtU7bsWsMLyNpbKXKp1OG7NpyDME/KGYeQiIlK+YUBdx6Xfm9oTzMOqB6rU3Fhb5Qf8JKJ5dE+NfeWLw6DDCXxuU5WeDQAk/UkbrSNFwsupY99ZnC3fCCYVLbleY/9JdSDJy6J5EFpKBXmyrCq20Mlf1as9H+mGDzgHCElYDWIKfEry39Y8u7r5KVTobmHphIbYSUl9rQEPFRGUfUHdmCt+3okn6L65duDlqgL003SpEXn73VKKJurKOYWsrEoChxJGI0n6wtkp4T6c0U7iZDOk8sHUHcLAUftJ87VH9Hp0R/oHPYUIQ9BVBWlkf1hTa7HkjUxeM6fAF2HPcM06P5ikFO78sf+zYW3r5/qy4VbYYW+XeMPnTkSD2QgbMHfvAdjPE5k/CI/U1WHCNdA3YyUOi5Ki78UlkRTovOW8Eqt1GZlCNcuLjpcVRgY/zvZirNP6k0lfvgh9o6BM9Rm9nE3CDEqu8WoIhuJqBSoenaf4pGtw==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: crowdesc
      namespace: cloudnative-pg-database
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdesc
  namespace: crowdsec
spec:
  encryptedData:
    DB_PASSWORD: AgAgL1QN7lMY7h7zGrCZBvDomOkYdNxGS3SSOZvhxNSdZ2ld+OEyQg3F1wKWyWwAVeboivDre2OJj4c6LSc/9cE5a2ys0zIEeqrxjn+vHji+fkfNdb5DC+tcQF9+zs7r1hJgVri5TmEjCaenlju936G4bSGLAuqid2Agv5qDb73Ktna5dKt9vuv/UJz0GnDXGronDlMaYuUaBKViGaZxlVC1UXLPZL5R9zMl2ofcUh+8KdmZm/cl6KqWvvXARURw8SEwJkv8Ew4Z9e+/D4Qfea2Bbcq2MZfedPwh9sxo9dLOlO/Tetx1hGhUkntrnZY0mXlyn1/aSbOv1lv2TmYe+AhM1pJ38rg52qF9NKSTIoyIldwnQPp46DKexj1TJQQxYd9QUVQMhgvk8Io2caoTYQIyMBMKAP+LVMAsF3CtKgZwJBs9X0FUsahMWG6ocETFaaV73Sz2r2lTYKdX3/ZU0B4aMAQ5BEiXOGsnRe6lHpiK7pU01uitT5fwA0ZJSQIafrse0zht2MRvItrC5B6JDCLmOqFLt8GleLWcmZgvzoVmEabLZncGbpf7pLDIPi5iVMER7+aHAa4cuGjROMgAf0Hwj/jkk5CfS0ztePXhc4lPNolqxpBEHKeVPzfYXP0acmcviHSgiCG+BMAnWxghf7a+oyjpXE9e37zFAGFWsHofsfTKsGSFhcDvV5BLY2YzlNRFRz1ZPbv/uv7O
    DB_USERNAME: AgCeO834F1T0Ym71jO5AEIPWt5Odb2VxaGjx6ojhia5+7Je4IbLM77CByXE/I4qgNCkKK8GeEqksd+3XkI4vm1iCmv6643Ucd7n17v69EvsZQevcBLJnR+lmN/ufgexcJui5OZbQdnsFrBV0qCINDHCXIND1nrM5HjsjiQ9kko6dFmS08g0bZ25amauf+QFRZISoHuAfrIyZ4wyNqJBoDKQc8GJumFTx7hgHUOSld+pDcmw0zPSmTlFxeapGyJzXXpS+PPnmNG0Dq3/jzCujdKoCtzWE5bVPpXc8b9VpFjTZuzD52jzTrPgEy7yvaZTlDQ9CDYfqfMUmw5i49+9tQF0t4DqvummSbZLAFGqNsmmP0GZfEPU/jYcCEFdHRYSpDJY6TCDYBckTxQTTRJLoR4lzbif8IWaFkgx6Q5UrL2ffWeywez2VBMf1B1GkKA1m46ki9QEDgXdedPgZHY+69PqQPGRWANCkttex4WMgGd8mBoC1OS0cDD/2SUt+ioHRm+qVbGvmKoybMnGGUlTneYDAXiZgcBoTyJjYuE+PpWNnFfx2OV8CU2wrYNRVGMJVuZJYdkwk6CPcC2K7491kAXEGIkZY4u3Oi8Hlb63fp8BEc5IcK8TG/U/3ce/gRRCXXhOtS+afWr60FNLOwmg+WsUcR97+6v/D6B2ThG71YfH0nwZEfTe439VvSG644Ov8YEMBn3oQLeLycg==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: crowdesc
      namespace: crowdsec
    type: kubernetes.io/basic-auth

