---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdesc
  namespace: cloudnative-pg-database
spec:
  encryptedData:
    password: AgCLDTxFxX/uFvwyMCFWrkRYk0BQWRr6CTwss2/HAgCCC3QsXXkJK1vO5UN0+pdbcYEWFpGo7jF15Cs4cLZKnA8EohHXwUxTilt4zpiPm50l4CmVyJtOl86ola5dk7XzmGsAAssrvi2Hp7gWoVyVGkinkDF0FTQSHl94hCkx4GyBW8eK+iF2qfVlIFuS0myVNWlKEbRMlKCUoYptbSBbU8Nrc7Y+NbsdGxo4cchPZ98jZhwLBcN5eWN3cat/ED/LWwC8BqioYSCO7i0n8mgNKPY6AYlmEL4Qz3XKsnuY8Ng3JTqLEaqTLnH0vdyXSOH2f1Yb0EGBKpspb4NjHPdzhFLWC7bl/GfIMIiGmKnEsDMG3L8wTu5RYWfnw3S3w5vB/wGpLNj22GyQk4RLXI0uQ7p0o7jAj8XppmqwIbkgQcqID9I82vEmwkvI24z4YH9C1AH/xABbB/UM19dYCQ1waktoL0dfN05WlIpJgoItp8CoCqCzUg2ttuhj9o8SMsNyghPvGxIAKW7wc4kV6qAZ5hkeNTxhEzvARC5Rv71LZT0PALQPDrK9IRxx57zUJqL5PIv+FNzNfg5tzv7v8EJECST9p9ZXoPY9lwMubeH7iC5mr52MCVawbb0Pd3JHCnrg4uspCJ0pKTnMd0FD9ibxM5gLEzaDKPMGBFx6fapg3vXgFYI2hSQNEexMNgbZ2ELHbxA8SXCcaTRlCOqu
    username: AgClPvlyhGMAJRKpWdJ7mpRez04Og/+AtIhjg/adOWNNxUmWuMOzLAcRQrp3tPQlPOrQr3GDb+rCdcIZYWja+1JHG+DtvP5B/YEw5eTMmheML2m8uxrcs279msOrwJqfYc/gvsNByChw4WFuY2HVLLqOQHLiNJ6uqujtO6bNe/taIl+jyryzPAkF5s21Lp38HeUkFyeNnx7OZYu9Cpe4lW56/xElYU4ie2BQrR9NdZ10jC7L0HGoKTJyiNcz71STCtrr7vhxiKUX6gE9VfRO2YVlh8dr1oJRCVIoGh4/3LEmKK3/eFdc1/vNB9YTcXqfxuaEmUGn6+AH0zNEVvZikfn2jMo216KiEtf6/H0lrthRJrY9GtMItoM++D2N6RiIN9RJjBdcHfYCZf57Ne/xBvl/9qv8fZmftXaCfMuhUQj+k4P3rVkqI0cNK4O6gRFoHM9PFHeRmSrm8b1vN8VjLn+yjvHflYQoGJ7WVCTlqwae9F9St4EQTaIPIJoawBnklnIqKQQv7dYkR1+7fNE7UaVnEmZInUB4ncm+SJMsTEAuUFwFNoHi8v/+29z4Ym2tnY7A/Ny7CZzsWUa/1zVh/iMGfYnvSNkSSM4a+FVVScU8jrsQHmdlcBWlqwslA1hohTqrTstXQ2MiYr3HAggggRFpDFp2yDFPHQz9e4w8LcTVlX96hNGMbA+6IuK5ssOf4UBpxkNnLWw1Gg==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: crowdesc
      namespace: cloudnative-pg-database
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdesc
  namespace: crowdsec
spec:
  encryptedData:
    DB_PASSWORD: AgBFN1DA8DoruaP8Wsm3t2dHkKb9nhKHVmMbYIwX1SVOz533ifI2Di09TLKM5qA/qMSxWg+cHzCWBz3EZZn8AgtcZWtq5ZA50FRINA5aV/ZkX8B+XjJ0Pe48nADHsmh/amvweOEL6yX2P9TMDmDKZazRCLbM5Nfl/NVfu5hMsolZSUsul6Xhgfbws+QjVfdjDZGFuHyI6fjF+coSouoY9+ZYJjnMoTZzlFfhZ92/d+sRBNUMvOH+72WedIETN680t+Uz1UFiVw7IkJ8xw1BRnoFKylegGXU1+4Uuao/Fd79IgOll425hSxrSdInO4a3AnWmmcdq/YrcG+4I8O3vfu7MJOhygKn8X+uapAJc0rx9hZAoGsSowzKQg6ifmp3QAHACeaM0ME+5VHRHzfQD47fwfNM9xyuuVuokWtQZT7mzKlCT7f5Gl3AlQTmzoKZ5TqfO3kw1vNEg25VtiZQH7QEuBjhRb/G6T+XbvQk/tNJlIDIxwF47AFwmb3WI5n9forQOZ5Wy/ICH299V3NSaDkgTZml6Dk16C+a3Jf2am5E3itO5vaHipKpqQD50MA2OVHqPIdzxhRJsfYYcxMa3wqPim63NuGjUCYf2+GRqBablKWR5/lRj2kEt5psowqb7CqLinsNNiPkRVx1dV/gMksWuvw3a6E1a6V2npYfXfhy6iDtYAKk2c2t680UK9LdZMP5ErcMBPICmGCXOq
    DB_USERNAME: AgBZsPeHz8dYgog7b0Irq84pOyi0PcsPABASI1ebzzg28vDjaoPNRwLx3lDD+Kkj9VXR6IwBhwteESJtk3RzmENmAguohMp7vW/h0U5yRTP4mZYkhYWXhBgk5Fk5b80hDZGJ4keZ+VcTOpumIJipBLXe5lYemApKCJP7IdurIhyBK5b4q+od9toUU9vJgtNrJyQGfzulOPIs8dVJOVLnkv6FUzXSziwgFE9hTbLeMvBFAQbGWEImPZEJ3oHz/LZ4FP6ikfmvBUerq/4eYJWMz+kbqxvRqOyplgoXxLB9bcsHfKVAiHAe9bv6PEW/l51Svsd/VicH+VSrhJ/QB/lzVhcsNLyFwaVGMKZ4BgoyFg56PNEyjdeuIEklzr4KzFFwgsf7Jq5Xx0TkaFMgsYOK4x1DMbgvGqc15m+woHhp3/Id8Ef5YB8lh7PmNVJZKwkDdRlyeQsBnBna4zVZ7iN0yQWHeDssqWlhr1AfG6HofkOdqZLdFkTcXkh2BArGfy/Plh6ROx/7+Vag7oLYmc2+/k8CU8ktsPg6mILZycRt9I8j37NGXcxAvp4cRyDwOJURFDJYK7Irsn+Fy9HF6EmVThfHFWsKp+p+lkEEPuDRQtcQgr9I48HyAOix9o1QDwMN0Y1wLa3uGCEel6hmFGjbk+9bN15+YlFrd7Azq2bSBsUiHQ6mH1BQ/Db0lUahIn1yZeRJot3wrSwJxw==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: crowdesc
      namespace: crowdsec
