---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdesc
  namespace: cloudnative-pg-database
spec:
  encryptedData:
    password: AgA1BxniyjzM8xOzDUNNZ/XkmbD6016QSkGY78p4AahqvGjPsRtaDgCx00AD3seTsQ9WUDzwIsvJpfQvZkNLB3VPYibBhhPcRFWcvhMMT92mEwK48OuFEsITvrokmRg07ub+cZ5eFU6pmEedLG2IYCSYh5Cz75JMFeLVc7u0v/Mo8ETPiW2Gi5i8ozlsxMdFlBQQHOWLUupll+6nGNZXlqNqVPTn93AKSw6JA8UD8XqAQyLYC/yXMC6jbiAaXSTjKpqC0G8zu45BZWoKCn1/UAqLdYvHqqtsKtgmpJoMbsp3niGWcja51ww5hKo5w04cr9Uhe9eRlbLslAP1CkwDubgPO2fZqz7hhrniy4NXARr5dfSNpLzYvJxCQ6VPuwnVAiazUeltOmNAFliX//65weDt+d1azMWAQlTik7F59AI1fVzvaMqdCYNXxz1x3Sap6/EHke4T/nozasDiJs+IJifNucOzAk+m+7DVsy3sgqxrBJIigc4oyjgUZRCqZ0h/Cg98KrGxkrtVKF8tsiEuoU5MgX5qJrXR2zI2VmccujqS3xcPJnZmUbNvJKCZvwz5r48gbg5iAcxEom67ukUokkXXCTLJjzeAT2Gulnof1q5IZNaKNPLwivHreQjSQ/yBRlxckqg2KM9Qo/MCLi811FJ9D7vrnhfCCtS1tLLYAUJO5sPSK60RjV7Q8nNpLEj+/0b5ybQalPM+meN/
    username: AgB8FRcCvp0W9LglNEcHveuaNuJjgXDugasiMirQPyqaGNPZFTr62Iz/0IZIRJObCx3/Euqjf1OPgbGdAV2le92GJUMIc+NyRtZxhniAn5LtGew2yGImqlZXELL1T1OvquMG1MjuPfov6uRszTcgjT8blrXUf1srMhxPK/TDoH4jftr7hrlw9FLT2U8bLkfzuqgcy7yAlvnOh/dV0Y9xe3J+VfF6VVeNKgvIeVShyEPBorr7hUBwJlYSCv3MCk34RmFznWC/Hx58FYYLK9uVqaSYF9D8ZHUXSAz0DcjwysRzKsQJ2Ywf1C+7JKMzHfAOdKjyy9MC2oGZev2h6wx+g9JVBUD/+cFPpuXtL3S29pssIF2T2r1g8TU/uKDkIFWHip8sNxs6YLhHWX6pP6FgBtZmPqs6OR70tpmP27NghVflDFSLj7Z0XxhxS1WuAJpaDFUD5/oQjecGwHEcGQT1oL6dUlF1fNtgJ6WTGsvgSubgjbTKL4eLugZUEVNAuvPkmZmKrdTSL5fAHtcIQfKSxIU2/JUCTlm9dOBX0MOgJhVXnYbpdzS0o1UfWg50qME+k9SAAVffPLWX8HezcfyQoV/CvVGvE4r2Vxz1ki78RdN0Z4aTfeCvJ8SabHAN80n1Fb62pCtq2VHFjwkvChW8LBQ+VFHvppgofR9T1pPjlN5To7rg/EYqWsl3+NINLqAveaEAZy220V0tpg==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: crowdesc
      namespace: cloudnative-pg-database
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdesc
  namespace: crowdsec
spec:
  encryptedData:
    password: AgCBwylJMX0RnKq+8HmjNZ+8ZP+NIxb8LIyN0/9A82pOfdlO/4LOWUfQf7nDfXjuo9CrTDHKGE/zmBM4EVKCVfU/tkwnG645BEEG3kO7a4mKLhAKBSiqYBqoD+rbXeoIJWMtfVTEizbylKHw8FfHB9PITmb/ZuAo6LKDuxYsDfw1DV7d/BKWU7E6AMmjUeqZwnWc2pdN44LVlIvzClmLxxPpCYx70YHgoTBlcmbTIp7+WoEEo3NVfh1bpbiHMA0m4bexaLk4y5YnJlyyPdrcqYxDAJUR62ZVeLipinEj0ZCa/FnZhhC6OWA3nw6ioq0WaJBSS1h6HkzBBae8S43VoKTn3wotk3aMpCWQS6zp1R/Ijv96/o9B8fmDKzlPuM3WfcyFWUm6OfYcvIm871InushQ/jYSBOBcvgxTROtNsgYj1PBkk3OQlgDeSWNtRSWHCqAZ8B0xiD9FdLkfXTKdeeKjRxTWFwUWSmP1o3xznjwWC87jQUR1NYV5aqXIopt/UZ9sprlvZX9ife2TbHcp2PUs7CCN1Brs1QDeMlKFkVQP+UE9dNLVxVkv25/b8VHpVN9Dk5ImYuq/ci2ad7lYy2sdzK4shr0/ttjroOQgcQ3VOkSBiFyhnr+tM3i1DJzM6UyDyNlBOzTXZXPlYcAz+h5ACDL8ryJC9NwudJs3UJ5hznupnJm0w0ty1uxhgUwI1Ls7Oye1dSTY4rpa
    username: AgAYSdYcWyD1M4Q7FKe4zSbCcWyK1cdAdJZ8MG1ib2i5pPX3AcuwpEohH8WU6TixHLXTmTBzDqtHJ5OfRxH8e6vxNYNqKsdH/m0mY4+KCtC+ykEYnZWHRV2KR8YRt7bv4Y/eaPOqiQ1Ers2m0Uf2aXZt/5KZ5jPAYkzQpjQj13UtYt+UiSHnUks6Kh74HRR1ghq4eIG83RGbVkindiWQUPbjxIa7hmMBWSwAAVU3hOgB5twWsqzD1WPdo4wGRguj95sdOvAQ6DWJVYvtrG256EbtOTiYA1b4WuW5OEtZbDrxUup8X5Rwdu0YrRa3f8FklkyWeP/A4y6QKxXm0k4CealqWHcztpj8cUO/L6Tm6J1V5PZAtoufOYlODV5MqqtPpbICBFvqjO3cH3fW007Uwg6gjikVemW+VH61bKOA05ZnRn/UxdGsM6/TOq8BiZgzm5w1yvlScRd13TvF1lX+pjQiuAFSqNku0qqtFYC1KDMgmG23JZANJY1qTU+B2Dl4F4YpSiT1PY3VtBt+4RJ7O7KHccjWMSF6PO3pq/7IVR+D0Op8KjtL4c6FBiWfykj/1pL2dfaFxJc4SrvYIC5nu/pxVIo58ok9/Thn2hUKeWWG3b+eQmjtsgZo+vsBVxI3MkpdRJPIU0a/depDQhNzYs/uYuYK04sHo/T/mXhp7Xz9EUAf3BKxcxXXVZSYmfuZoXTtPXta3krMlA==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: crowdesc
      namespace: crowdsec
    type: kubernetes.io/basic-auth

