---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluentbit
  namespace: cloudnative-pg-database
spec:
  encryptedData:
    password: AgBUmjr1wIS2anNyYJvva33u/WLXMqaBmmNxoF790KKdGQVbFoDO5OxDHAsEKsPq8++YoMyr4PUsRPzaASH9PnPdfL+F5d5ApPlXSFdxS3S5jMblVuW4iNXkx3ybOSt/AF91cV4XuKbIWqVCDN1rvbPmQ69LaTD/XXwkDEKnhyctsWh4OAyDqhaRIB+MLPbnAlgPk5LIzLTDcevl0Q8TjyYCJOO+BzBdDTl+cLJBmbvXRubufeigR053qrbdnKKpHjmpISDcFupf8YyjVUQQdjvNWTKdltubZXRMAonGD63F4cbj6O0Hm0Q24bHT/49MKJ6byEImcTLehKmyQmfCDldBUpNAvUBx5RSSXTGut03tXYRV53kNxJDnYpsvi8c6skXOxFb/9uZ4Do16ms9Y+SRKwuqpH65hGPjaIPTAXp8uWAnz9qcp6SOrcEcmHIg/Y48HeLX1wi4O1Tz9hpSEeS8b/pQZUfp+w6H3iI7TNd7ZhxOTKWZAapozZUYm/rF/jvQ0lLiQJ6tlSZIn3esUrRR9jOlynY2l6erA7cJRh6+B0pqLDdgIap7ciNZZZCwhmU2oQzHHbxNssoldZv3mrO/BfEHX7qRQsI/ywjSjTUO1VDwCEIFIikfAXTCjdslAG4bGHkW8H4xXdRfdZzdj8kVh5kdZ0bzfW5ksADJB//kRy+8+x4L4AHOhJftGPCXcLrMSZ5I7lhySPmNa
    username: AgAFTM60urheMWqu+cjYPAZkJs5kgiU4MQXP3lb12qlzHRq26sPecd6wssWp/Rd0dTSKnlgVkz3ps8lCl644Bo8UsSj8NiYQwZ9bxTLA+VioSYlWEvbV891aEV5YBwZRBRlBZWc2oCM14+7CoqNy6df7gsAxHyjC4l+hPt8D66RMvg7ks/rM0YbkJSZmp8xEhSLnl77e3oCi4ec0ZFtoQafG1NMvQxeZ+zR3/dEIynzdeDcicjJTyGUihKuSSv8t3ybh1F/dTz4js8Rs5HTWdyxHYF2CVji+U4b8W6cX/gAee0AvsCVK4yxTHTFx1Ps9iXJEwCuKUQGeC3CAnIVrZPmA3FoUKlQtKprdMXNmXUQGWXzAKjqSTCFJeJrmVyKlmrqrwApcMTBxyYbSnuVKhaToO/JuxHNzVMZGD+BDsFkm8HLTlocLvnmE+6eaclqk1ikQIT+7rryLbYK9RBipdyW4uEFkVzzLcP/bre5ibOHRxyOiKcd5t7bA8voWjuQ9HJQGyf0UdAUJYnQk78fGGiHXENlxaUhgAqp6xoS14VzQvls7br3/J7chu1CK/+xr9OWwUpi9InjJJx/7+SlrwZPDz0no3iSQj4NEvPU8eZIqyuycattaeuoG2IezqpsDToIhDlFcK+VUluh174zkOSO0+Z7sHfAmkuwZe7uVb37RFARgzm7rXvaB2wlhTfzYRhtqACOL8OhwgtA=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: fluentbit
      namespace: cloudnative-pg-database
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluentbit
  namespace: fluent-operator
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAJv8StYcik1UqY4E7uDX2lwCV2zhJfEAltoMM7U2na/7PvrMmCTmP7N3xe9e8tmI3Nn7pAkMe4mDkGhemYqo8EiuFNGnZ54GbkipyuIkeH1WtuN9pCylstdBaPbOhokE3avKkH7gDnPRdRdg1lc2Wd/Lgu1GTPb4GpP2p528+1grGG5gzKDj5sFkwY8jm0t3T1hq/s6v61dpN2SxXXmKb43TZO75c1+5IOSty8oV2ubJkynEKkEMmhPJWhWU4oJqa0FIe3nsMh0amvZgj1Xn7QtN5JyQMl2aiWOZvTuK/QJHF5jMXBtVWJKzAzBfs7mlZ9rUJhkU6YHTJOT24yo26/rI5OCpzJ3XHjvtQMwyFu8EObNOlPGYwAPma15Srf2iiojghUrcTNkC75bcpsvCNDKOc9P2t6QY2CHGttAL7kpo8OYPtTd8zUsEzF9L8Is3gb9Pdeumrip76g8LXZy6/OWX5KScjGPykMyX3f/eVE7qplnaF8YeNYD/UPq3y2UiurNgZJ33P9MgL80exX/eH/s3lr6f5QuTI73DlmAjuhJBvq7L4Q16uB8/uMm6qeObLpENJ5WR26zRwfbI2M53qHKTiA9vpnDJSTR6lZXUeY4w325GHXHWBEV9+HjVmQboWLJMGFr7kBuwoGRLzLosVqehZ7/B+0SdNwUzHDT02cHK3gjlI4n8vDUFJTyPAO4W3AJuSKtWoRgwsK
    POSTGRES_USERNAME: AgBaWeeyM+ktTNoXJuV0QbwQPOnffQEM+j41W+211TxKiw77dhXISykhtYvERMgkaC8pg1m8OT4qQmZEIz1WU1uEw1Dh0pfPblPphzX1B44KYrGd43EWLqu3Pw4eBp2cx9mSOcWVdBYmy609weAwbU4qRmoMMPCLPExaKDn58CS40RzZuKmuqj9mLQSCvZ5a+MXEclFEIk7I3XHfV0BILVhuPnBFQBiaJZnJuV1fiPwW/SUaKtRENV0WQ7r6zWQargUnXVjZ4XFL7Uqj7GVRJo3tndTd57BC7GWMpwXC1qDP/vIAX+qUjsG5KkohPm2wn55NW7rOF7Itc39LxIKrjSDKln62h/BFCa0H9ddvJiW+Xjdzs7/B1B+eTd/z9THgGs05SUJOJM0at5wKWgkgbqxqRnCuFvbFR9/rDQPFd5nU1x0P8FLKQHQToFRGZGL609hmO2rcLnf6DArE32lcGivgGwZ+knHstNCNrvFsHG/G5AwdrLMiAdQj+gxSOhumK2h7vPP/pMPkNhRYhtbVWdLiMIkrHaqcl95a08rQMY4lFvtAH9uJCJi6VSopBjdblMPCYGiRD+s8L0RZ53P/Uuf+wVUw0rtDL24l+s1dXH1dzVUYMCXJiZ29Y1KgJ518Wnfjo0xKRArDGLv0RecTTToPfnmVO8rrn9GsoxuWKsYi5L2jy6+FiXOu0E1EFL7BS2glvj8fi22794Y=
  template:
    metadata:
      name: fluentbit
      namespace: fluent-operator
    type: Opaque
