---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluentbit
  namespace: cloudnative-pg-database
spec:
  encryptedData:
    password: AgA9LByaXo0czJNL+vcS99BnuEGTMWrnAmXST7yZw1p0EGaAF2tWLsBHjxV7RO+qBWOrUlZ9iO8U7rHAk3dHrG/y5EidbAsLOKvArZI7OcG8NYWWfWrzQ1n7/oMyIwURNeuw24yq6O/fj2Djj4PqwjdTQ5oPWvZ+vzFXtX17XlEupwOU/WEyM3rc16jY9ckEg6HKyrIcbLqlCTKi6LQcqjVHyHlKpcmf9xW+8e5S5iSv6VD29NjQsEQ7iOFy/mrM1t+2qGjgQCz4JOdr9uvOmKd0SCvsW0shWglTZV3plefhLDSP3z+LnninjXuWQAhw+WQbm5a47HGWBu/9v4RNQlJ/qP6BgHOz56YKlaCxWOWBAQ9XKNuF/YNwCCER1nIXpKaKVgKEACUNzxdhLcAItwMJVDMG2tU1nt3sv6a8tjvGjhpBHpFxxxALbdHeG6L+VKc5WCRwMN4Kr+ItYzxm6mPRvaNegb8NQfFuK/RkLlaaYp9AQku9nmvC0xY1pb2KnKnjY0PE1JQZgFzJv3FcWDiFcoA6Y4i+ROi9NO//vhedMOzVTxMQLgpUw3izt3VMz3cQ9XfFrh1wxVBUQAka++Gz+6syJZD/vPdfCFEeIDMH+y2e3Kn8Sok3kgDrn0Ms1Ae1eVfVDQWhqLsnQTDdYuzIaM85hXNWa0nW0OLzIf5y2+9TULI+D4lCNd77KD/xmcA1aN1gcwuIyV+O
    username: AgBm2aoKRwsT4oanO77HR1KbRe1mHU12GjKtRN10itiLENB8vPOIynl1hPPuG0xbdvnmaknVt+3VnEoq9PZhAD96wWKQK0VQuWScoZdL+J0TyLKN8yfVWyfKzJWBzh91AoplMXrPVZCaZzXepg7qJBZrlnGf8ScqOsy63dk9IRBqppDWCw4/6NABHU09M05xRiwjUenPDYeOv/ReKWJzMp5a1APP2JEY/qloHBYkbh5ea5E+PrF/9o6xA1C298s1M7OE/p5NoSLiEvBxWG3xoC7XKQt9z49JdhD9dHQRfbpRdeo/MxouacVOTkbR5GHtITBas/dg27TA6u+q7qBLa1vVpEK+xTq1A7C6SB1Lvy7VKxkNbFtNiUcl8Nt9VBdm4EEoD2jbUyzevBfbKflBlgu9wt7ZYhSczNY3BgQneCEqIndPP+eDVNt2h2wMdIFeoZp2DeDJ9m/qVZB/tUIQmBpmV6qbA/CqIQA48gkukC1AcnGD0QJib58116uwgFaDxJYyA+euc1PcloD3ghfT+hGdrN2bbqEJSQk85J92awOV7Ea3ENH2Y33EXf9vSQMziKzX3rlUMgtOWArSsrCpKpQYWteEbLbKpaEfF1CNoyDThqR1DG91ra/y8xXKlR1I+LhfnwsYGZVbdxl06XfhYn5Y+LV5P9lM2zwuwBHFvye1g4IZSf4tKLXo1do36kHS+dOfi/cvgFTKXQ4=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: fluentbit
      namespace: cloudnative-pg-database
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluentbit
  namespace: fluent-operator
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBVh2BGXhK1ub8w4LrVVK16DighET1XXcN+s1K9KumlY4/NFDrqkOWzvWWJh3Zdo7uwA6fcU4PzziiKYMD+OuSTMGTTA4NWGy5nkSOjgZDHTkYMUyxpjUZDDvU+HwDERJJA/YQwx9d/GNu2pfsqes3T6qoReXsww0Br57ddf3aSVcwCxKP/af6I3IU/JpnosDL6M0AWOjpw3LMBCVf8CSNSlx5eRO2wLds952cjZZ8wkD9nzSLCR84u51QOtTWAGn4QpXc7BdxUKWfcF4oyo+nZmuiWnu5y/ikfS9mSr49GrBZVr48Uv0ftd9rMG0mRws834uFz4t24ij1fFxBTTbRj8sOhM0M4BqCtsISWd7bMgiKYBUc6BPpGT4D41yaw90wi6iRQlqMcrj2WH/UBOQChRGDrEYWtysg0WIXgjJP1nXHxzOEfevjA2gCiez1dyayjoPEyWCpwQSdc+NqqmTtlKLvXttd7RUBguNX4AzI1h2vD/RjMe2+c1/N5gVo5eZlYGsbCVnCVsrAB4YOzM59RZ6vME+c8OnN63jFIcUcIk7BXsjyzCk7+KaiUvBtuPJ8HfvgYuYI5IyT/0UPcjxm0A/e6mFUf0b2pYiB18zbJhtyTlH94sa6ipJsasiHp7bwTOobPyHYNj7qI33zhpWj5y2jg2lGvvp29DSRPKks8FEoZ73wuz5je1ubRTRNqA3hCsK03UpL939kB
    POSTGRES_USERNAME: AgCXduh3cpmJtFCcw9hXZMJ30yAJVyWcyAxl/61qGOO1rGlmEhTBw1Jgd5XeJNag9T8li33UN9cipJsM1o7jyW02/aisrDLGvqTxlQ0E/RsoTBr1GGqGk9oi6XUmRKVGVDkgTPW9wuz/TyfhBD8g3/1hwYbpXmhnJRfB5QG0erJnovZqKPS/FnX/mgtGtXW+I8YCz1KatM5/WnEJy8ipVzhNnUHgux2lu7rzV97iyf/tE6ljxdVZjdTJ9gf/LoXo7J+hmqrzouPEJ6VvOXEdagX0jWbcYIz8jWlIo5mge2YmZdYPfdD2QvYLIOYSnIotFBjtvALcccwYJf8qoDJgmPmulg+MHapOxgafFDTo3dH4Wqlox7WvdbERDEsyRh1AOeR2cHOntPC8FqFOAtcda9xr44iowTHGD9vZ86pLVsPwopqfRwbPJs1sx1nPkfZ5DD4T9bRUkULiyW0aJ3bPKX4RIimK0Z3i9M6UZhgAp9SCLsL8gIxTfDxjoSRRikqxG8790HHLyoLo/g87zt7R6EjJxvQAd9x2OVGr8JxsQVuv2LkhE0YVJV+lXBUfld+OsfXTaBGKob5xGo/otK5BNuRiDBQwUCYVQ1GKILx2kOfhn9PdO6iSwb6ikp3f32iKdagWmFU5qU9FAFQtigQ5c2RLbejpuSYj+7iwwSF/fx9KipHCUfDBUY2LNcXhePFtuiu82y9XP3tA/Ao=
  template:
    metadata:
      name: fluentbit
      namespace: fluent-operator
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluentbit-pgpass
  namespace: fluent-operator
spec:
  encryptedData:
    pgpass: AgCFsOtQJBqY/snEVkm9jBATS7FnNMVCbf6imsWKY3tTe3qheu4KIfAHOzc5SjP2W68YsnHr9/RGgCrdHnR/MvzcCP9oZ2k1hnqp1/npLHmkUh3jwbhUAeAKszkodIeManSxPCe793P6/PoXDDQeGi6IpFhBdS3RETolxm4R+FrFIqzRiKhY0HI41/msa9wmZt92mXpZiZSA4JL9d/gPlof77ro198cAVVzDInzb55TSlRtIFRkTh/GuB0j8H8mnk7k3qK7PBNEhVmL2aw2s2nOWfsS0uc/Bk02zObPaQpashdbdROgN235GSzQhp4w76ceooUFJyN2xYTZhW4sQdXB2zHo5DN1BriycvsD7uSIlkYJZQl/OOPO/JaWt4JmLzia0S8k4hxJ/ke4RwB0wm/AU5rY2SrjHPGdN5/iGXlEkk53RrYxtIpd9ROOUdu9HIqTYsfqyZNZrq+EsHMRCg1qaK4w7elSUgClTOwuWuxYUlceY73h8oYabQHNKKv72m+qbN67tFza2mkT6Sdl/U5w70kNBEj7rda/hJvzRKsacxG+c+JML88qje00xPznADGHkKLBE5x/W4RB2KtUuSafWw1PgmVziXOglQZY/+QrbN2KDootn3Hk/FvQ+8TQ1+EEJV7b+72K8wP3Nsh2hJH3slBEDTjqIq9KLs0yerbRVLVLEsPs+r6wgjvGVLmS8BZ8bBFVGj2gFbeWiEarVIGf7/r0u3NxAyEIoowf7KKEc+XlSoAx2wQPGCHTmanC4xT7ht5y8D6DerbakIX8T4dJeM3vOK0ZMxokAziv0P5T4HD0J7HKzduu2sCAN7A==
  template:
    metadata:
      name: fluentbit-pgpass
      namespace: fluent-operator
    type: Opaque
