---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluentbit
  namespace: cloudnative-pg-database
spec:
  encryptedData:
    password: AgBDWE7UkEro/oinLGBi2LwdXH+jDmdiPboLS5I009oSfAHO3tIY+KYVaHqs/HNafepV+rlQKgPQaVzVeiJYuTYsygJWoWecjjt5XeUcntK9ZzpMSL1Axls3R+nrGni3JSiU44LA28P92rtkUSAZEpMrwJW943JyeU7GeprRTLBKImbvxtG8g1Nx9Gky/wq4rpKcxtDp8KdPVoreNcuamColrVmeukMI5HS+H1XFEdepiW1JamTb2ZDT4v1Bklj77+ETYV9MaJfyFBTV2MDnrXzH3nQbi/dnxu4h8o2mIEMtsj74+amaO6wegMGvqi9yZli+m4HGC9tz4qd0m+jegoCV66CST+Gj5taCiRQ6+JDExr87Ble8IKNoBJ/NSVZ6RWFfCPQ6r+DIAyDkPt1AFnPpv7+kUzOHGhLo6e3F+vCFihgQDODsldAHhkwpKnofHhbBsAnWhruz+M78ro28oh4Ui9RKSrVwSCDDVTPkALS3bHGxzhADKgv8cFczQVTPvvB6rrP0HFYiF1As5dgAhsXUReVlTDZ3RYyquSS87FDIPu9sy8SKI9024MNU3LG2wWJSPf/U6ks3CbruitS19GNadlmBVZ536yXr4lYEq+UC52cbAQM79bMoGfMHSHHEXxy6d8jEUpU2PPqo2Fm+ZBZT3bZzrkKtv/9v2KqCtbrlvOYh1rYZGLRCKU5J6srT9tpeoLfpAe7J3gGh
    username: AgCUJqUb/UnBIO+JChrg/isC3Wmz3neBIqVB2WuvPCUWgU/boscT9/JubKJtG3ShBpdCC/u/iBQZDMrTTdDABeHs0034axTr6davQvSCXhk7KVUKfefccAe7ngB9kValqjFdnqE5ckW0hU6EYjz72r5sbzVt6a1EWD8/BMNFc+5YRLwXw8JEZtPbst8zJYbLZhNmR+3J/PEVZnOq8RZalzdzf3J/MWVVNMSPpHEwk3DORMKhGZ64Sdl2UCE5jhnK5NWGcZgJI1swi58BlChs6FT3HdYalLdwV2+1DuLnKHpqha6lo+IiItVjnt7rADbXvA7eSk8/6c3FgnKbBAjJnOiKFysNIr3qTUG6FgB4j3zebS2vYA4JDq24nW5/ErNv81Yvvnb/jfQgw0uz3cO5SbrubjJuaWrBdPgSRichJQLFaQsPtga3x0bqwo5FA4EjPNPjBTOV0zyQ6RMJn9IbrTFuELBY66PJFjJgoyoosdi4HzIuUa2FrmcGAFLgC1fmQvqaxIAETBMbkJhxDzxbHOKTCzWLOJ3msKuFtxGqgk91xSm+vOysNNk3x2mtO7qWi9eyALwQxn51aqkG+riyR6H39ZfjW5zIk2xDNpJcjVpUMZgfVPF/UQT6OYW4WVU5X+UTIcJyfa1yugQIews+30Y6RMfbNVwbM9JVuEXU4VJOId/KWQxSyftODiXs5xfoI1r7Jq6WmXtTtWU=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: fluentbit
      namespace: cloudnative-pg-database
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fluentbit
  namespace: fluent-operator
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBLYSFm5Fq0eFNzH2TvYkacI7NeSSS9SMtuDPQj9p/ECwEZx7Hvlzn+xx4YpUGT/fJU4tT9TGjsafqtaCVMxJRyot7qVZKmgdkQCxlv7Qw7eEui63Jm33Hda3d2W4rKBSUjfRFUyieJwhEYjHGeFdWnGFawBzOk/hbm8RYEZNqpdCY4QR6HI3leND08+KTDmNvKtv4Y1L2qT3Q4KyTrHwhhFi0ooPt94yBX2y/aStmPmc+LnfriQVX1DZulufoohrJ3wQwcXoR8QleHTqLCHS/rh90ECq4HqoVBstKwj1Jj+Ryk3roGo7wTXO+n3AnPxhCxprBrNTCy0TgyBvUReP5XfxQadJ93nPdPhHLr7DGuvGlGi0akF6LDo91CfiLI+alzQM86ZywY1SVB/nXc7cYJ4HnogwoN3o8vUhCU0o+0N3HyL4rdT0HmQHvbUVcxVHee4o83KyKfiiA4eS9AC/EMgOVN20L7dIo5Xxp5zJNzgdf03HzoCk8h/3xEp2ZhOpqhjIrmJC42rgHRUPNLH2lcMDvBkWYupOsMvI/6Fu+Zd+51TwvohuzkwBsKVoqwzOFjSduhsWOfYjEm2WM0G+dyEYusMkluqIsvCkWitGisQnv34EaQRVQk5uy4NHUMZnFlllGXdmiNMZ4TKjdW+hqE5JV75ASPC9vnQ7sjtDhemcDNoMHgQE0p9gqn6x9R9L+BHgxH1BNLlFJP
    POSTGRES_USERNAME: AgBJa6dNzquHWQQchUhtrqJx6GEzy8yKvnkEyq73XDjeBIX9iE39CDxEWdLANegyqcYf+UnOdsrNL9ydO8uENHBGT+CmqA+4amyUqYXvsmZzGEWmg3PMewZH/GTrysYLkCC2AELp3yPiaRSZ8PTeBuZJJ9Qocn2r8dK64T3hqOXkW8gsQUiUZKmvo8KYjnRq7U61A/v/kLnvY5SYx4wK809DIcUYuvMbq6vwK74CA/EQANV/TmjJnD2hK/mdnEY2fo33uryefxkogELXk4YnWfWvv8T+/eKdy3DRN/iP71cjiEfe919+6UtPLN5JgXAuSRf+oSU8NAxNNW+S1GH0wVmrHx9HvE5FDWkD/XyU4QfcDAM5zlH3hqlj0CWLlapqMFWpaOYqmz6rmFUQ/1KV+AKbivEAhkpvOcswLATCdRt1RVQigAlL6P9U4T+4c21hOgeJM6pp8fAuxR8wZmabheMr9BSGYaJ+ssUer1YPlVzMHUuSLIkEOCW/glQsksTyNCiU7NWkeYQMGHcLdpK2cPYvPSqel92w/V0enU0w/FJDGqKLxbhsyY2ukCPQDecaA8Nkq+XCr5x/siSS/+Yf5YOE3C0TgEOXehPLM9SdQsTxaA5yBbWyNNf9/bWSE0xZQTcG6YHdbevFitO8YEXA+oHsO3bWbNxZs7jycQOPzhDpk/ogjCgFQyzZyLM+0PJvWgLJIhKJ8luc8hw=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: fluentbit
      namespace: fluent-operator
