---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana
  namespace: cloudnative-pg-cluster
spec:
  encryptedData:
    password: AgCxx7PeAaX0jXeBR0D0xWqjT/CXoOZ/ei5ca3FnvWPqRgckGxQiKa4/xEvQEVkoDx5e4UqvkF32eIfGKWPZkrh0UGptk9pyXNDOcPJeuhEdq556+xSbqAlewx7BmYIrGfM0JBAQBHbEYrQy/u16gbujbDG/wIxRzMZEVT7IO7MIzGW59fRD0B/ozk2R464mmvSYEHy5WLdp5leToBYsXh6Hgn2T5Xzk0i8xC9k+AiCR6GNgTChW2nXGJPLUjpG8bUzjOBd53N2qXucIaGRwJfHpFswJYRji+AVbQ1Kik4EWV1n4eeNWpKAL2IeMT6D+4WQJpeKO8bUixCsKxI/SbgEzxgYEI2dtyVI7xVJ65RJEPtaDSexsgOiuqmkv1mqLryQvo9+zcOQzk0Qf5/4V4LImIWGKojxP5Ami/F4RwPFuRX3LOp5UJrs6suOyVuKRy/5+xaLA6a6/ZT9OcYAjvWrFF7GsEuvuLGDyeFuEIxhzOU1kebo9zkgIQ+T7OzwUBogfXIAzsXhiQb4RrtUUJynIQCkqBXi979c+CfVfx0zVkh9a4I3MHidco3FJeEl+JNJyh9RrXj6XyVsSAOh4vozjTo+Ag/UC4xtU78E3IKJ0RSxoqTbk/Z7cX7icL4inSWX1WL2K8we1UiF1hbdSNJkcD7V4LI6QnIA4O/NQCuwmBRQpqZ+GhRyVjfEIHGtQrxW9G5cbUApOJqVqv8VP1or0
    username: AgCosviy2l2gWCpZBCm3Z4JuBSVMTTX8/hdqteZkeHSsCIBuOS1DlhpK4zUHvhEoZlUfPc4n8WyHqZBwwNH/vfOY2sC2Vqi2tTvtWrvpXbqOV9I0Y57Fd4cw9foQeoUUoJVg4qjpT9/AiWLCgbAiabIOctFx7oCylsQmHveu0C9CDEru5RzUZQkNAzSA2fm4AxtnIjqj5KE5f7OG5eCOHwLDCRCaFwM3JZ4VctN+mSD7G7GTqeNOMx+60y7TVcbp9icBrT3g4kZ7VFlFay9clY6yqVIZprZtryrhsSK/uY2E8/aHsw/PnxCUO4eUgZmLSZ50uKsSPkN06Wq9qaircD8EpqUU5I1HBiCxzrfrlqTww5Twp4qEcgMqAElkHmP5jmtD/894Q/vKELgioJ5tmcu6YBfdExYlY4RIAeAKyeji80DhxprWgmURrk7BsQztA92LCzVXYW/2rYm4IL60K7nAji43WH+GNOg52XYabaILisOKl5O41w4C8RzPysyPIjzVTd1rBPYC8+nTux6Rz8ndD4D+pvr0yexY6KtEC87LtbFvyG0nKgD7ALCRZ2XgXjCDykAd2zc5pROpEH4EEoGuF9Aga8Hz4zt675eFBvXX4cPN7WF8R2w2NMucusfJXzDsHb+D2lfQUgy4P3zAwBWvcOdTk4Wp7WAsrrKef9dFolZRG91ihSjCDBsr9RX6B2Is7YPKucWv+w==
  template:
    metadata:
      name: grafana
      namespace: cloudnative-pg-cluster
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana
  namespace: cloudnative-pg-cluster
spec:
  encryptedData:
    datasource.yaml: AgAjyonMmMKj6MbvipXk8zjxLezgJM1W086gD9xesPp9lS2ktK3JWJ7aYoEJshAS+Ay4/PQKrb0OqqOjVmoQ5LYlbB7CaEGqN2MpyEYAsiaBfscMEhyJYwbOpEpOHW6Of+MNOc8msbz/k/9K1JSgOYO98iGZZOaynFdzVAVRtly6GBAPYcu+niafkgQ5T4CWI3TJWWxWZCRP+1Fg+zUhevcu2QOfJOgF27jm1t01RtbKeDRIMxLKVstPHtvAt+/WpC2TRu3b5OsBLZHsjCmkxMdb7Fifqzgsttf3ncleFYUMPL5WkMbt9WgU0cf+SWsQgyQY+iqUsCyCT2tiQtVLuQf985p8L1TnYUzqCnZbnbfoGyd2QMki3LPvbPRaJwZMnmQ5RXAFdBN8/JRff07W6VbrYQPwCvlzXvdkxQMdityl/3bZDua59qSFipPBh421guf7LxS/vDJct4m/k0m8gtj9GeoWvbCfrXqjvCergpAOev6FQbCBrgwqm6mBuf++Dh4VcVKOzVPNJXIxfsJlqT5q6krSnFtQTbiapixW1G85QHvo1cA9Id48pSR9uD6FFNNqqsta5kzatGupbsZtuM1bqOk8Jl+FWXhDnStiy7kOO9W0rmKxNB4a0HiAZVZQudpY9mCe81L8+mQ3oYODqj0Oi/mEntix97BHeOfIPyhL46CHMJQ+X5VeffnJTt3cbyDgxCO7ga100LjlfQCgrw0gfgQWyAViPTLjQ1i6gmaWtpK/jPy6BPMqoUUTKMA51yKu0XO4hHmAy17LuS9kajb4+emxtQJmMx+om2XkZIO65SF9agERaAGBMy/8CG3ykV6MHlTGYbeJDcCoBbSZss4R3Mugo6brr85smEIk0UweArsd05kKQPc+SDD8qt7bX8VIAWt8HSw5A61WfK9g7L7xA/xR+NUNUWHUs03xNjJZmSklVcNzesV2R5wFLQdtPIGaZah0Q2FU582toQKYWJBCxp7CojjREz+vmBnNkf9cGZtEjjbfwf0GKnk2f0c0ZghzYaiRl8TFBzKh+GnWRxaRMpVaUOxxJ75Rng==
  template:
    metadata:
      labels:
        grafana_datasource: "1"
      name: grafana
      namespace: cloudnative-pg-cluster
    type: Opaque
