---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana
  namespace: cloudnative-pg-database
spec:
  encryptedData:
    password: AgCAw4xWniBMaNb+wRlTQAka8VJuVvAs0pVYb1yd3TN8P6rKBPSx17FtM6Us1omwBxTa16OtWt71M6t9Vm7ha2dohMi5PhtbJIOPkF50bHms7lC72Dwv83UH8+w3/JekFWwvqv5XC97GXigMI8XHQln0ljn7BGwzjYpAzYfTlHaF6mzCFta1FyHQFFifQpzC2wgsNCbI5PUoG2K3IGQMjpq9aORWtP5i5BP9hcfE445w/UEHYAG5yzyt1lENvfmQw/KbJsZ/ZssH23MVpdHKU1gniFsT5/OUWg+Dx0UN9u/oK9TU2ZB5GW++QcL0yFvytX3FWv5TR4FvLRGHRYZc+NJBQ+NGdea8QymU45L9eI2hBIB0Zb3P546WNaOgRMH8CMZxEWYTMcH3aP/4NsJLS0fUyy5sDdL/LqeF17u7X7HtI9b1Dv4davSsjUzI4MAiu3v13FWJS+VqGdAFCVbozGhFdE3MMMy/HuEQFYmCPCZYAFqNfNWKevO9eYXL42XSIqOXt/VNs2PKtCTd7XZuUDjOnJ7NSuznEc4xeRPTRHBH4D0NgLHeQsDyhiR2QMaIPmbXfYOdzMLiulnBoTXoTXuiFqQmgIdtlzkeLl1mRaOVCEgXM81Xm7AN6TqSkHIFV5HSFHrwm6ik62V+GXkZT5t4qRzk+PwpTMXPy3wzpARbySZLxa6m2E44pKpWMCpxXh5On33lc5h39u+0O3f8CObn
    username: AgABycPwlmsVyw4Itgi7VurMr4Kn2SsXvU4fPmN9BzHz8uZDxmnGfgbJcHKuy17rINZ5xhGFkBF4F3D+dPW9C+KNUGXx4fItwN+/SX1LnaX2kjW7LDpDQFe8bVk/WQUuLBargqw2F/kExbtIO4d1wkaUwe5Y0TdcbwNOyZO84OnBOQU3hmyixHjbKfC5HIwNl9MlB+3vSz876uExzpgBnfZE8POwjxzL3icQqtrKXK5YNdFBlvQ6Tqzig+YScksK1x4J9GRYC5QYPvIyNkiuPTNZRZdpF0jCyblxIOajEfDK3cyFybnU5gnLIcg641kkvxeRdsOiSfF9Fvaus42UFlPe96WgPzKvXBOW6TO/oyQl+twpVCIutgyNzP6TgWR2tfSBG+Qsxe2yPPMNLP3eXJpa6IFwDZLnsMfCuPrmqyO0K3xscX3aiG5DN++TDlI+TVdJz2+C4QDJbm9CGwxJEJaCLOTYC9IzT4ySzk1YlTkQVCxe6Aw76iz8kOCgCJuUoLF/mKIj/wTHf3GKcZf8AeZfbDvE0pmCW3KWv2nNNkQZn3JVaN8M9CtTjZMPxbadSXSmsY74WNnlaS+W0an2t09I9sXCde9YKJUM22k31KeYya2imEQqMH6EBWCFLYNuTOK0DP9FrnyQcl8t58ULZJyL9J3Mbu64G1CiMw5xAEIXsljIT4lSMBSLAXnf/97NSdXl3/kweG8/tQ==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: grafana
      namespace: cloudnative-pg-database
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-datasource
  namespace: cloudnative-pg-database
spec:
  encryptedData:
    datasource.yaml: AgB2Dc/s3Psf+SH0JP4INbOfBi9+CgqDrtAUcHIyJ4+ep2aWxaJuTSXyl9FN1k70Jkm1sG+Nl4Ih3JQYw2pDYETevoYLL962wqUNv4VzweNAQ8PXWMrwPfg457xCFnCLZY2RDs6rHMEYzrk+j5ZaSYKWXF8zbhLfNip4uEZNzinboer3YE+z4g5DtFmgUI+UNHUH6nHy2yd1YU6RNtr/IBEZvfrhbZweKaI4cnR4mlIJfcG/t0Z2Fu2mLJT2Xf/6h37YcWt5BwojFS6MPVb1VwcSC/93HCX7wDMMn0eJZF9tGGZxuyL44oGN7DF593MN/L0PZzbfJDu29oDB1r14cxi5r6MIOERdSZm2Eu7ckSOXj+ZX1WBuaO1WCOLrX+5jqu7wXjZCFEpHVMnI/DyeyyUR2XwlMUZH/QVwyQ7VM86DxHrixnd73NsRq6YXxirsfAOAiimeAIecjo3wivMLIUMwO5kEtk482drOXu9APoWh8yaxhimqKOuL+1YBIHf/mwIU7jPMehx+xdd362XXepBK6z4rAiBkOe4WTKyrnwTZP1HmSrYUAj8cAWpfp5f9bRC75eOwtUncatzt9NUG5+tP8u2IoSva/R4Q6nzyw/Dor1pIzf7i8TNJh14IXjg4xaOu1oeKaaZZNTd+mWksARIciBeepLaFSrID9xVG5Br9+2VUlL3zCD0205to2+xoWJfnSMJX8ATwnu7GcjR73CJW2q4qRoFXapjNWBlELAgXi7LXis3eR/+4XdYvuxOzLUZk1S+ukgNvttPC6BGjF5jlRabufMu0AuY3VJYyd2Il886r/MgbQ/MODb4LK9PYMkvVczMdTRtMagFZRXsQPeIInYkRcnF9BvcMDjAKvOPn1e8vLQR4MF8FmwKZhS75RKCvZ5LicDpJZgXgEj9AEGhoIMptrwoLFsAQOOiNPhTZDQeNUzqetiD39TWZv/jOzvJpFpr1EIAeAZebmfPsBtvKu1jVbeuU9vG2US4VRrz3OsMfudoobFDmv7zbgK5eUN+eyL+BvptdZWD0u+Uhk1uP7jNNWVQv8MEy/g==
  template:
    metadata:
      labels:
        grafana_datasource: "1"
      name: grafana-datasource
      namespace: cloudnative-pg-database
    type: Opaque
