---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana
  namespace: cloudnative-pg-cluster
spec:
  encryptedData:
    password: AgB1eHESqdcx0JmrlUA+TliQFgZmzwBQBm2JKrl2dF0JkhiKFw4c64oV/ehzN+Edf7+Egmtbya/JWjDtO2W8imXUCkrd8NjYfBaouEUQZwvEmejb+ESeIKnKwQiLnrq8Bp0ITxy+24+KMHxSdwLcr/ld91xbXdETAI5NsCJvEsM0qhXYogfe5FU1MQhcRDoHmpbDvCv76r/7uFupeTFLpO3Yt0BSeZs3V6PvrBdCCHoGMXrmgXklqc3Ok57Y+C4YGmYZ3jmNscgst2+HAR4t2m8r1gNWCl0Xjw0fK15ZMs/+twWma17GxOikVA+y4K82VdtMFOXaUMYczElGE0OpZy/RLSrOlw8ULMIYOwE9ZboLPII2d3teSWw8+EJka2Eh2hTRYDQjXD7n0lvZmKCN0u0/FEXa7khTbDRpZLJP088QLaxMnrT9TyftrX8CM7hZpxXZSPjyB+EhE7MgyR3XqiodsK1YjO49eSe7leyIrEtUPy7NbqexVRAB1ndJM7oExw+yMktjmn/uD1wW9kP4BvMEwdwZRavlpCuHW43KQypHHgUug7YcRqlI/R6eAdKMrZHcfNCgRqhSMPpF/fRux1pSWg0cBPg9BD6RLIbkWj/xAHeCCf8pJLgUA4EF9hwDeNIhbKKJ3onQ4jbN3q0r7EMjTl8Y7ckUV6KSzeN/xYBhGDd3vf2nX+u5Rc68rI4iyqMjae2ZKCjMfGQsYIaNnbTe
    username: AgA7O0Km0zuf59KeCgC3es2vS9sLZ63yNjpRuH7uLfBUoH0g3eSLWNo+8AYJYPM1PJcG59trrpKyk9VvXw6edunvzFOA42TcSSZWgqQDzRFdqdVvkKkcavKdW+2IcPKhQfuonzzDdzsOhgOb6G5fFf5elTCxvZpBTRPwofAylDVUO5lx1C2Svv9zCP57pJCxXtlhnRkEzD1vj6IPD7sHhESdelFFlPPuzLW/9isF0maWuvTNuxQiGqnt4PVlQlap38SfBJ04ojrdMV9h3aQySeTfoCecZclqC9V7sHltSfSs3a37Q1iklRfjsgfQAigfMGixcBC1fjbllMxb9nxp/GLFFunaClKr+hOID1u2GdOpBKBLVVlJPF3Pv9bSxts0ADhgBG2k2DelPFnlY8X7hE7EBCXdDPV18HtjzPZjQHinWZMpCj54uQTkMKXbhxyXnna7/7UO9mhThkqNp3MXu9nvXmYRcYejkspBrM0jpnb08yD9BpEbIDE5yq4/n1+k2ySprN/fcbXjPKumK5UEazEK3rAvlPoxHET/i0IxHF1oPwvIMiuqj/Xs0oYMm/FhidzIrtjOa8kX9sfxJteqPe+YKi5D24jQIfOPOUj/ObVNuiKh1uSk6ndjJbGcqQT6EjGW65cflEw4TYHykElsK1eymkFGG59Yv16aL0jFMoTSsElNWTVa9cWYP3kXJ1XPhQQOOj3ABKjJfA==
  template:
    metadata:
      name: grafana
      namespace: cloudnative-pg-cluster
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-datasource
  namespace: cloudnative-pg-cluster
spec:
  encryptedData:
    datasource.yaml: AgBm5gdCbZGNPsmIxfjmoe0WDZZVrGxOZN2yZ44rqEqz3HadHWnyurGQfwklTQkBRAa6fmKyDFfumCNmiXAfUkQXnJ1koI6CV9xNvw7F3zgIjBAPO86HXJUjJh4tU5Vk3KcSIuZddgfG/NOlu4owW9P684YrDmrDnsLNAZFe8XfvTbSAu6wJdE2xZ6RcVR4n/iLbqiRr6gRU7zLGsIvj9O8pUnxfklmLmzrqASlS2LybK+NFSFw/jHdh6JOc7gERbkdOFsip1eRyLbTGGMQZF5zrcpJQaGfMlSepDCuFtgCTRAvQUrSzUzVAfdAvdyx138iyEuUez9rASDuoBqCDCd3rnDI3vKJpz9hb0MT0Z1QLxuEOwgGRTgeBuUP9IDuzwDboyrTwwC/1V0eMUfq9io8O6wtnhKU2p/NXadlT2L3khY0Xt2rqGXhFDNJris/9wKHALRRkuWLSLNdjrmoOqMkHDipg55J19KEcL8x0T7879RVXJyNx16G61zFOGhii+9P3vxMyZAgdq7+1fy4x/FWCZYNwE6vLppHZF2541pxUafXw5nJMy1XxeEmMaBmwMMlYt0y8R2D/IAXCpjj7WLWjKz0v/yFDzKsvhLHpopn3JLUWcgzbU8MytaMxS09rgpXiWYHC7Fao/eyGTfwamMSYZAOx41wEdf0BugFCtRvWUCmOdNHUkO+sEUzbXmjX59SeQiBOj7rrBuUkbeERNOqIVeybTonFd8yJoeopCkq2FC8kzDaTfVh+Bt2l731brj76LOpS4S9PWWTWd/xv9q1yEp5aMBCtkP730/Klfx3b+FfnsGZ34st6SRiuIvA+R2kuORTxq0Z1/iWQVWv9XLeY4SvOFySiJmXp0M6VOt7wbq2U+4y/pEvUF2E/SVteIVXyWmo08p4jt+oM67+iBIKn5ZA9ESQ+OxMSw/4pu5Ah32pSgfFLInZkhp77B+2jDcMEQAxqdAo2zI9bB7hr3VTcu+Sw8Zc9bbNG9JSvI0ubs+eOD9gDkDNir/7uoOkayC+VcDWYvA6jkV2ESKSI7RQHf6CrGQuyO0UDbw==
  template:
    metadata:
      labels:
        grafana_datasource: "1"
      name: grafana-datasource
      namespace: cloudnative-pg-cluster
    type: Opaque
