apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ras
spec:
  refreshInterval: "24h"
  target:
    name: ras
    creationPolicy: Merge
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "ras"
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pg-password-generator
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: ras
spec:
  deletionPolicy: Delete
  refreshInterval: 24h
  secretStoreRefs:
    - name: vault
      kind: SecretStore
  selector:
    secret:
      name: ras
  data:
    - match:
        remoteRef:
          remoteKey: postgres/ras
