---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ras
  namespace: cloudnative-pg-database
spec:
  encryptedData:
    password: AgA/ZH8v2SOSLuF30MlOAz4K7EnIxJD+tGeOMV725zSXTAE87rAJNdhwXu4/BbzneR6URFfV6zPtLhbiMu6siJ3joZ5Kns+hpznP4ofupBHxBqF4H6CGI2Gmc2fhM37A7ZzV14ss0bkFi0Cvm8Zq6KU6skSAB50UgQ1xQbVSDepLsjGThvEDU1lfP+oYEdSpzZj3+0NhOknaSffXlHs0O/SAnfckY5xyFbEK38gB/Rrr9Wv7zBJs0cGO6SHG+KSuFA3WfrzxZn25qid80rAKx8MgQ2/aj7ghdSSEXiP9/3dMiFqt341CTSiFRmg2mwTL75c0DEXNKJsawm0yiQ+mFa3O+5oJARSQnfPbx9xBta4VEvBBPxJBiMrAhyeBOWsXMdm7AhjYJoEw5iCjPVXn48NIMQoWULYLCFCXm5TN5OIOusXtTVprj6qOat+vSWeLh7ijD/sFl1716lh/vvhUdnFfsq+I+hPvwRDt+29NzWy0BncTtXsBehwmVCU2oCBpnO0v+mISOkQg+TEbziNueJ+KhOM7Blqj4caPFed9V2s7NrpC/P97pahAnK2998Ni9HYeuhe6/SD05mgm/pFFl7xRZKRZfo4PcbuTyjAQBDgnws7se3t62RgBcQgBlEVzz2oc50SvY3o0cnVF3Ai3MkjFphrIyT/ZGYM5/hmJFv/kpVvLvMY1hw0+/SkP7FrbGz12YMMGSQC6KGo6axEJWWII
    username: AgBMbWIEzIVsGJ9deh4xIcScyDx2WaT8oVN843Jp9U0klayE43KGBNRvqIDSK1BD9Yy+Lzr70W8b6bGPGi7gOCiJ9y7La5Wzji8trRn9AunhKTI+7b8vSGwhQmjB1Z6ZBNz2RKAWjAS3ZhgOXwBqxEcE6uYG3HXNIG50DL8PHosm2lme7OhVKwmbCvvWMK+B2zyh7/xrbJ8168dQCL4iOft/4YZ6l6SGTY1/1zryl6vjgXPhzjU2XWLUj8uWFbp2LxMwfe4FVv5qvBPGhr2qN1tjBRutJFP6nenTkp0mVxni3fgRrUpYSBpGk4RZft9YwEBwaHqv35Bdo0l8qTsXSRPlogzBYnIjuZ/0QNtP7Dol8LAF8rCRCsJbgyGkGNoh8ANaHvr09zmPCc0eckdyAP/DfeOT05U9FykUyKGIq55vOgDxRpPH0K5eg7KJj3qGbJpklJDIry6vn7vODWzIiiQ5PthwhaSjp6XhfV9uPQiufzVsTJH1IxmUquwdXYKv8GFkXK/53C91YeEJujwa6R71ctF4M9a0KTPgbl+xP8IJGJpF0dRml8ZG5xaybvNKwxErZZNFBCVmtBPySTI2+wcpQZT1k/fZ8GyKRdenLdhAUe/lWrVLMNPgbewDecl9qGCsKBDiX9FA4hjRYFtCoKQ7VvVWlK/QEV1mjQGRE1pSubq6TI2F6OQHEiXWa2AsX9VBgcnG
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: ras
      namespace: cloudnative-pg-database
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ras
  namespace: ras
spec:
  encryptedData:
    DATABASE_URL: AgASta111IyeEWV4Zf8RuucZ4TY+dHGOmBi3A6YXbcAkHhhjlshX4M24A8oVpsEjH7noCniJI4RbURLJkROArNIL0rLVPLNX14dRLHUj75jCezuLoY8EQM2VICLBzVRKsRi1H1bbDv0mymIZnsTrcgjchlRPXna7v/gYalkCF7pPJV3XU/5gfnnqC8TttuNw74VIkzJ7t3ihxSQg7vPDMNu+Pn2jHijQ9X0y/2soYUsvn4zab+Of+oOCSdM/QVWOXTS4WdpJSYE4NUKN/gb6RLW6lUWgwYGcyg80bFi1mKFhxxtXFY6t8RCFaVq94pamCh2UbzoHzJAJys/YIIKlvpsJnK3f5fHuY3dlJefcSdXHpBqjdKfFgCm0g/UsdjaaewMxi3fkEtx2ZNM8WoUQiCqD55u66LBQp9Nl/FxWrQEeUxoaR0v+L76TZz+CN3h7we/wWYdVfvU8PE2KfD5RtR6qIF9GfOEGnjr6OM3EfMXyaKVnbn2N/BZwydbjgsGBfKITDFoUB6bMnBrm4Gh1EOCbFahJuarmc7/oI3aRHUAttWS8IO9Zjfz1sLVjU/6oe47q2QCNMMWLpdoNrCGkP8bcsaCoEpUQYFif57bPnR7NozS0WoLUOMiEle/rq8/2aPznPx0c94/gnWPruZi0ftRAiK1nhhRvd/QgTCo0V+/0nCxiqSziAhL/PmeqskoE4a4sZdOW16zYPwUzpovOn1Y69SWAIynn+2DSna4JbASWf2K1Ms+pm4wljkZbcXRZSaX1P7hLCESu3gtmdzvjhNXzvE2xSUx2pTpHOOoeUPflRQhSGdCiEcd4sfdrh7IFZgTjsoCotDw=
  template:
    metadata:
      name: ras
      namespace: ras
    type: kubernetes.io/basic-auth
