apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: cloudnative-pg-database
  name: red-proxy
spec:
  refreshInterval: "24h"
  target:
    name: red-proxy
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "red-proxy"
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pg-password-generator
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  namespace: cloudnative-pg-database
  name: red-proxy
spec:
  deletionPolicy: Delete
  refreshInterval: 1m
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: red-proxy
  data:
    - match:
        remoteRef:
          remoteKey: postgres/red-proxy
      conversionStrategy: None
