---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: initial-admin
  namespace: opensearch-cluter
spec:
  encryptedData:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: AgBPUcEMmAm5cy5qa2eCMkf1GHBnNUFxoMxB21q2DMHmjJfmAUqgoXk3W6SEnpoK6mmzNaWCoqIy0Kmgq1u8dClz8d33Vy5H+1uTOPFnGb8iNmYZIAr1X3m69clryYAgQlkrT99iEqYJygFpIYZZkg+zkyDbD1IxZKxjgugrW7UJa4mjwXWGjKUbpoaWh2/KpPFE4+xZSrGbxZvr+uw+685e/q8IRvp4DTHalCPQRK6+8p892uRVHxWxY1vcj0HcYHA/x4MD5YOdCn7ZNzavs9B6EnNCrVEYHyljvXoTxfUXYxE/p3RwaCIdDx0B4bo9kD3oURgbH4FzbXBS1vyXWaSuHZCFG2+p63IHZRFcjcup8RFk0TLlgZvGofaeLvFamj+ZdXdhkaR1AUoJbyChGsa9FRsIzIBJszSNjtnC2/ZCp3M9CX3MlhabAtYsdYbggsXMeHPiNZu8vP7tLcjT/JdR6AvVkw3sWqIGzIriI6myu+Pn3456ob4TVPPeh1m0yEySdEE3Rln/1e67KbfG5RPb/FRpqODx9I3n+Ou5hDIgTepURCrdFsv/Bwm0W18VRS8tHWVyeefnJqG5cH6zmqL1jUcU3Dr6mpy06dzemqHmKiihOjQfrvafXkhamkwNy0uI1J2Xo6v7uJjaZqav7ZfsgzAgljy8WPcxRUiV+LUUGdCQkMpN2CwEic8qEZ6cINzjdCYJt2lvE4tm0p7w/7VV
  template:
    metadata:
      name: initial-admin
      namespace: opensearch-cluter
    type: Opaque
