---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: initial-admin
  namespace: opensearch-cluster
spec:
  encryptedData:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: AgAnLYEeXDrrP30Z2SdAskw/FeevuUbuTCTrYmDk4/hkAdyiZukD5+azzYd3r7KxK93qBz+HaLq6W0bmt6bArBvLGtvjptmBsKSJPX3jlOmjOGI4IKguC8f98W+BahFlcfoCpa1JZP8dBWXVIL3F/xKB9yYpbQYx0+C3xoJiTxlciXVoAK16zjL0Sk4fYyoeZB6gyAKxEUnXvbnFCVA4do+O73XuGlhIQYfMqyUnXgBIKdyagTE5ACkOg/izb7qFXTCHgoetr9NhRjdZqVKlx6UhOKsH93MKBiGwqEqtFG3mwKIYZ0dHJFERopPGEuboCf9Bki1fL3UYi/THpmR0NgNdbKt2Orx+MWY6cpRIVOaUkFblSJ2Ot9qUfoWKjMn140TeBk7sS4GWnLKJW+SOr55G33WrJT3Cad0nPTh6Pr6C8CYcbFXWmgB0FAQvjELLftPNMMzaKkMJZfZT4tjB5mw7yZD2jXnz0OMr0B81RfFXvogobHFKn8cOkLpBHXhY1o5t0F1sD7Bd4lifUwVA1tPJZOaDKBgQ3h5sylDcyFXypPbT5kP3U7UkB4tj4m9Oir5Mpv2WA+UUDEWk1Mj6fZnTN9+iHBfnVQoQUUDe4vSfA8HUi5nVtrpzS45SqexOZ37APnbSid5OZeyuNPJB8pZpEPqXkG2MdrD2/1WxR4oA8rV7RnN1MjgpmT2YnDXNAlgqeWWjEZloN7tfkiS6a/tB
  template:
    metadata:
      name: initial-admin
      namespace: opensearch-cluster
    type: Opaque
