---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: initial-admin
  namespace: opensearch-cluter
spec:
  encryptedData:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: AgApXWacoDG/eR3yZv/YjEwGHgnzK0hDYcXPNs0gYZhUhBXOdHBrpiadGYFKApIPWOsNW+Bg+gJ48/Fp0TuNtwkkkNKqVzrlKDYWKy2CoSwmFSklcPgL8zSH5OUyYkpWnUf0oLdJHjntnpi70kuiFNKB4JvtZRVwfK+4W7WNWHnZN28NI24P840xEdBMaHRo3p1nP8yug4LSjhwB+NPtxGeT/KH1O5Wq2pNFbeHcSoIGBLV/gv9Kc2tJbr11Lt34ZuBUA0gDWFaTQL3x8zv5vHE4T3FCq6m8JTrCzhFCZG4Dn94fnqL0ZRwZu1+gJNB7hyK0lll9hrp38oQqfI3oT36MvvuJzgzNplQhxaf4ZFNv3sEG0beBAGJtD2ocnhDeMO4ePagaPE6ydrRyg5LpCfTFOsXhrcQVd5Rie7b2//vCqhutOTyULwu+W+47EceIqbVH/ezlz5RXQ88Xc+LX2pCKuc2PIZs+IenxMhoTPr1AdzRyF7OFSST+GT9x2oxJ6Je/4IbTJeCe2/3au5oxO8AHm5+93HZZ+93ZMx7s1Iq8qaUY3khNCZUT7rAGs1ojxQmp6rfLoZ9IJZV2qRwwdjWm60Kz1fZBG09VKbdL8IhyfapKJcyukAB8W1B4ZuzcFidf7DSihjpiX3qofs0nmfQMbiQA+xFgLeU2Dvbb5DAEB4ieSNFCvSQMl+JckYBBaZ5H2v8srYCmwKWlmTIeMiQ4
  template:
    metadata:
      name: initial-admin
      namespace: opensearch-cluter
    type: Opaque
