---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-api-key
  namespace: kgateway-system
spec:
  encryptedData:
    ENVOY_BOUNCER_BOUNCER_APIKEY: AgCE0prLOObbyMPwUztYq/oj3B7/j+dUPqv2adohzLAYEoA+yM7+Jx/KuRBbS6LHScMMae3LI0QEZsNTQe/73d6hPBhRH7jIvX3jaLUfl15Hcub5G8fpkYwgKfaNcU3YIoBzJykzaVDU+gXsDfFmA2jKa+I16tpVbXFRLFr7GOI28feO5y1Is3xuJLeP0yPfd0hKGH9FQf7C6CLukzsUEj7VYF7CTusy/GmSloiNT7Rr8q6DUs5B789pQmGx+g8NshL4NY49MlV6Bgv1jo/uuL4mekSZnqtYzH/nUnGTQZ7eGS2iwsEcQNNjHA9n65sWS6RJ3gpJ4XYh4loqWd0OSAmSKWGCEs3bKwBjuwaCet6CL2MDCL1h0dX0DkwIvFAdbHX+ta1xCGBEbvoPoocEdt7+XBTGMXlpGPoFhTwgKnbsLS6ngVzbZbRJZC3F02GtKVyclhLpALRMCpyN3YLmBwwQn7ZYQ9ccD6SbRZnzp+cbtuQUWcRQ6Msq3Qxqc+8qwRVmBWnKXc2V4GoHf/ISrcqmfoodC8zmdf/BXutS3L51zNVmbq38BarXTgtdsLNuzpjMluTP3Le4khgUeKm+tkLRY71sEjUtDP6fhhmW54nLwWwVIak8i7KwFn8+Aw6D/QC9Tkmj54zeveph5JAIWHwH4oscNi+c9LCDn5LtbgLw5X0NwMQNpgzKIM29iJOaNn02U+k3i0Y482oDv6Y/9Lqf74Sdfw04chUswrSatP29y35CV5uDzT4EnViL9wbLoxRrNA==
  template:
    metadata:
      name: crowdsec-api-key
      namespace: kgateway-system
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-api-key
  namespace: crowdsec
spec:
  encryptedData:
    BOUNCER_KEY_envoy: AgCVJI/Ammy21y6eisFp6dSMTEN/MTdu7XLgv/gs5EB30E8RvmH1+FXCz48e12jPAUkyOV2wOsQxyDQFFP8dnNPnt8WBVvVZE/Vhka6pHA0LOZxyXgHWygzMYtV0PQjulbKIvadhAkjrNaGjylUKqRKJgWeya292jkGrr+MAjWHFqPrXGEHLCPrjKREn/AXI+HA0xLN5Xns7hz/XO7w76WKqmPCegOb9/7EfM4wH1eaywvaCEBm3TCtpcGmMDRQ/WoiGb1v019/b+ErfUXTXZzqJDs2OjoTWVYtIGYNVbZBZMwSWFnPwNYYWXI5U5rd9GU31AP89bBkN1j3qDxUn35fiekL8U5uoKHZcJj0d7SdSgyOEqIS7boIBeMLtw3NtK5+l28H8xvaFKhmHUMt3XcqD7ce4emkCJbStLkd12u/8XTfRyNa/U1lPeBEaaGBqnDviB/r6mGPMYEJjbBndNNcRXPjtTYjf/DWJkKWbHVB2g6c4SLZ4udJ1kyP4UW+yzvVKt+1a2NXwEWkO6F15xjTFEUDwU62/M0hcA+lV2vnVun8ZtY3OMUnp8qcJikj70xFuefrfmmC8uKQJxe8qkYGWPDEbKktCESP/DxQ6sGv9Zlff7K2+DO6QuR9Qp1Ipozq0olXL0oebE6BXuFvP84k4Rb7sNMQeXN98NeSpkpsRc2Mys4TR8ICJrO85qxoHUJOgSe9oitT+4pSWo8If/oa7LTAKdQTkr369tPxqofyU+Aj7tzYz1c+LuPq0R8QdciladQ==
  template:
    metadata:
      name: crowdsec-api-key
      namespace: crowdsec
    type: Opaque
