version: 2
groups:
  production-dependencies:
    dependency-type: "production"
  development-dependencies:
    dependency-type: "development"
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "apps/ananas-music-control"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "apps/rat"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "apps/home-automation"
    schedule:
      interval: "daily"
