apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-root-key
spec:
  refreshInterval: 1m
  target:
    name: rustfs-root-key
    creationPolicy: Owner
    template:
      data:
        RUSTFS_ACCESS_KEY: '{{ .RUSTFS_ACCESS_KEY }}'
        RUSTFS_SECRET_KEY: '{{ .RUSTFS_SECRET_KEY }}'
  dataFrom:
    - sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault
      extract:
        key: rustfs/secret
      
