[package]
name = "ananas-music-control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
cpal = "0.15.2"
embedded-graphics = "0.8.1"
flac = "0.5.0"
fontdue = "0.8.0"
opentelemetry = "0.21.0"
opentelemetry-otlp = "0.14.0"
opentelemetry_sdk = { version = "0.21.1", features = ["tokio"] }
rodio = "0.17.3"
rppal = "0.15.0"
thiserror = "1.0.56"
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
tracing-opentelemetry = "0.22.0"
tracing-subscriber = {version="0.3.18", features = ["env-filter"]}
