apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: renovate
    repo: oci://ghcr.io/renovatebot/charts
    releaseName: renovate
    version: "46.255.0"
    namespace: renovate
    valuesInline:
      existingSecret: 'renovate'
      cronjob:
        schedule: '0/15 * * * *'
        concurrencyPolicy: Replace
      env:
        LOG_LEVEL: "debug"
      renovate:
        config: |
          {
            "platform": "forgejo",
            "endpoint": "https://code.ramona.fun",
            "autodiscover": true,
            "hostRules": [
              {"matchHost": "npm.pkg.github.com", "hostType": "npm", "token": "{{ secrets.GITHUB_TOKEN }}"},
              {"matchHost": "code.ramona.fun", "hostType": "npm", "token": "{{ secrets.FORGEJO_TOKEN }}"},
              {"matchHost": "api.github.com", "hostType": "github", "token": "{{ secrets.GITHUB_TOKEN }}"},
              {"matchHost": "github.com", "hostType": "github", "token": "{{ secrets.GITHUB_TOKEN }}"},
              {"matchHost": "ghcr.io", "hostType": "docker", "username": "ramonacat", "password": "{{ secrets.GITHUB_TOKEN }}"},
              {"matchHost": "code.ramona.fun", "hostType": "docker", "username": "ramona", "password": "{{ secrets.FORGEJO_TOKEN }}"}
            ]
          }
resources:
  - secret.yaml
