apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  refreshInterval: 1m
  target:
    name: renovate
    creationPolicy: Owner
    template:
      data:
        RENOVATE_TOKEN: '{{ .pat }}'
        RENOVATE_SECRETS: '{"GITHUB_TOKEN": "{{ .github_token }}"}'
  dataFrom:
    - sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault
      extract:
        key: renovate/user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
