[package]
name = "rat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
colored = "2.1.0"
petgraph = "0.6.4"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.112"
xdg = "2.5.2"
