[package]
name = "auth-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.91"
axum = { version = "0.8.9", features = ["macros", "matched-path"] }
axum-extra = { version = "0.12.6", features = ["cookie-private"] }
chrono = { version = "0.4.45", features = ["serde"] }
diesel = { version = "2.3.11", features = ["chrono", "postgres", "time", "uuid"] }
diesel-async = { version = "0.9.2", features = ["postgres"] }
diesel_migrations = "2.3.2"
dotenvy = "0.15.7"
futures = "0.3.33"
http = "1.4.2"
openidconnect = { version = "4.0.1", features = ["reqwest"] }
rand = { version = "0.10.2", features = ["std_rng"] }
reqwest = { version = "0.13.4", features = ["stream"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
subst = { version = "0.3.8", features = ["json"] }
thiserror = "2.0.19"
tokio = { version = "1.53.0", features = ["full"] }
tower = "0.5.3"
tower-http = { version = "0.7.0", features = ["cors", "trace", "tracing"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
uuid = { version = "1.24.0", features = ["serde", "v7"] }
