controls:
  windows_enabled_and_configured: true
  windows_settings:
    custom_settings:
      - path: ./lib/windows-settings/disable-telemetry.xml
policies:
queries:
agent_options:
  path: ./lib/agent-options.yml
org_settings:
  server_settings:
    server_url: $FLEET_URL
    ai_features_disabled: true
  org_info:
    org_name: ramona
  features:
    enable_host_users: true
    enable_software_inventory: true
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"
