apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: "https://vault.vault.svc.cluster.local:8200/"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lVZWNMb1g2T2pSWFdQSEpGNHpnRi9aT3MxRjZRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dERVdNQlFHQTFVRUF4TU5jbUZ0YjI1aElISnZiM1FnUVRBZUZ3MHlOakEzTURRd09ERTRORGhhRncwegpOakEzTURFd09ERTVNVGhhTUJneEZqQVVCZ05WQkFNVERYSmhiVzl1WVNCeWIyOTBJRUV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNvQXQ4NWRCRXJsUDEwQ2R2NTIwdGpNUkJzR0RlYU4wNEEKaVF0YnFMVmtaejZoeTN1ZXRpd1J1WHFaZTlQZnpLVkYwTlZXUDRUdERpTUgrMTNYSFppQ1FJVkN1Yi9qYmd2bgpoUkZybFBFL2lOaEQ1MEk2YUQyam5hYUtUcTZvbldoZEtMc01kMWYwRjM0aUplSEpYMjVIaGgweTYzQmt0UjFjCmRHSUVacE1FTWlmKzh3WExuUUJPS2FQUm5LT3FuNFlkczZGbVNRY2dhN2ZhRXJKUVJxSUU5Y0xRNkM2Q0Z6dVgKSzU2a0RPT0JKL2dST05Nc2IvTUs0ckUyMnJCTGhmQnJkWm03VXJLdG5XY3lqSXpJbWVjeVA3YXE2OGV3SWo2VwpnajQxR2hnQjFJTXI4SG1MZkQ2MXFyU25Fc2FEb3gvZ0xadGFVRU1hK0pYdnJPanJRN1F2QWdNQkFBR2pZekJoCk1BNEdBMVVkRHdFQi93UUVBd0lCQmpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSamtNYzQKenVnaVJPSTB4Mm1LeHM2S01wTzcvakFmQmdOVkhTTUVHREFXZ0JSamtNYzR6dWdpUk9JMHgybUt4czZLTXBPNwovakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBS2JQR1ZKVllhb2JQL3N4a1pHZWZIMmRJK2ZPRUlOUHN0MFNqCk5oV1JCOEFZOUdJYnBVQzdIcXlXUXF2YS8vNlo1ZzdQUlVHcFg1eFdtTUVJWUExZ3ZpZUdzeGdoT1hjNVIxa1MKV0M0czBjOTNiQ3ZLaXE5VFJ1U3p6MHNLZ1FKbUJIZUhUUnJLMENhNlNEWnBNYlJXS1JwQkMyMzEyN0s4QmpxaApJQVlqNThwSEsrcmJuVFBOa05LVE1MdmFSSllHZmMwYmNEcUFJcytHUDRSWFhlZlViTHgrOExXR1dzZkt4VEZUCmdLQ0FWR0NMN3Bmdnh6TGFMWVpDaUlqWUUwUW1VN3lOdm9yT3hpaXFWQjVPSGN6eGMvZG9ybzYxN0QxSFFGbW8KSjllNEpxWnk5aE9mMXEzejRsWVJoaURnelNabHZIVE1TNzBxeHJuS21YN3hXMHVQK3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "secrets/kubernetes/darkmore"
          role: "kv-kubernetes-darkmore"
          serviceAccountRef:
            name: "vault-client"
            namespace: "external-secrets"
