[package]
name = "rlib"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
chrono = { version = "0.4.45", features = ["serde"] }
ipnet = { version = "2.12.2", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
subst = { version = "0.3.8", features = ["json"] }
uuid = { version = "1.28.0", features = ["serde", "v7"] }
