[project]
name = "ci"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ramona Łuczkiewicz", email = "ramona@luczkiewi.cz" }
]
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.69",
    "botocore>=1.43.69",
    "igittigitt>=2.2.3",
    "requests>=2.34.2",
    "types-boto3[essential]>=1.43.69",
    "types-botocore>=1.0.2",
    "types-requests>=2.33.0.20260712",
]

[project.scripts]
ci = "ci:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=26.5.1",
    "pyright>=1.1.411",
]

[tool.basedpyright]
include=["src"]
exclude=["**/__pycache__"]
executionEnvironments = [
    { root = "src" }
]
