[project]
name = "ci"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ramona Łuczkiewicz", email = "ramona@luczkiewi.cz" }
]
requires-python = ">=3.14"
dependencies = [
    "requests>=2.34.2",
    "types-requests>=2.33.0.20260712",
]

[project.scripts]
ci = "ci:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
