apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-cleanup
  namespace: fluent-operator
spec:
  schedule: '0 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cleanup-logs
              image: postgres:18.4
              imagePullPolicy: IfNotPresent
              command: ["psql", "-c", "DELETE FROM logs WHERE time < date_add(current_timestamp, '-1 day'::interval)", "--host=cloudnative-pg-database-cluster-pooler-rw.cloudnative-pg-database", "--user=fluentbit"]
              env:
                - name: PGPASSFILE
                  value: '/etc/secrets/pgpass'
              volumeMounts:
                - mountPath: /etc/secrets/
                  name: pgpass
                  readOnly: true
          volumes:
            - name: pgpass
              secret:
                secretName: fluentbit-pgpass
