apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterParser
metadata:
  namespace: fluent-operator
  name: parsers
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "fluentbit-only"
spec:
  json: {}
  logfmt: {}
