apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  namespace: fluent-operator
  name: syslog
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/mode: "fluentbit-only"
spec:
  syslog:
    mode: tcp
    port: 6514
    parser: syslog-rfc3164
    tag: syslog
---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: syslog
spec:
  parentRef:
    kind: Gateway
    namespace: kgateway-system
    name: gateway-tailscale
  listeners:
    - name: syslog
      port: 6514
      protocol: TCP
      allowedRoutes:
        kinds:
          - kind: TCPRoute
            group: gateway.networking.k8s.io
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: fluentbit-syslog
  annotations:
    "external-dns.alpha.kubernetes.io/hostname": "syslog.infrastructure.ramona.fun"
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: syslog
  rules:
    - backendRefs:
        - kind: Service
          name: fluent-bit
          namespace: fluent-operator
          port: 6514
          group: ''
          weight: 1
--- 
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-tcp-route-to-syslog
  namespace: fluent-operator
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: TCPRoute
      namespace: fluentbit
  to:
    - group: ""
      kind: Service
