apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-database-cluster-backup-s3-creds
spec:
  target:
    name: cloudnative-pg-database-cluster-backup-s3-creds
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
          cnpg.io/cluster: "cloudnative-pg-database-cluster"
      data:
        ACCESS_KEY_ID: '{{ .ACCESS_KEY_ID }}'
        ACCESS_SECRET_KEY: '{{ .ACCESS_SECRET_KEY }}'
  dataFrom:
    - sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault
      extract:
        key: cloudnative-pg-database/object-storage
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
