apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kgateway-monitoring
  namespace: kgateway-system
spec:
  selector:
    matchLabels:
      kgateway: kube-gateway
  podMetricsEndpoints:
    - port: http-monitoring
