apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: forgejo/forgejo-runner
    repo: oci://code.forgejo.org/forgejo-helm
    releaseName: forgejo-runnner
    version: "0.7.5"
    namespace: forgejo-runner
    valuesInline:
      runner:
        config:
          create: true
          existingInitSecret: "forgejo-runner-init"
          file:
            log:
              level: "info"
            runner:
              file: ".runner"
              capacity: 1
              envs:
                A_TEST_ENV_NAME_1: null
                A_TEST_ENV_NAME_2: null
                DOCKER_HOST: tcp://127.0.0.1:2376
                DOCKER_TLS_VERIFY: 1
                DOCKER_CERT_PATH: /certs/client
            container:
              network: host
              enable_ipv6: false
              privileged: false
              options: -v /certs/client:/certs/client
              valid_volumes:
                - /certs/client
          autoscaling: 
            enabled: true
            minReplicas: 1
            maxReplicas: 4
resources:
  - secret.yaml
