apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-init
spec:
  refreshInterval: 1m
  target:
    name: forgejo-runner-init
    creationPolicy: Owner
    template:
      data:
        CONFIG_NAME: "k8s"
        CONFIG_INSTANCE: "https://code.ramona.fun/"
        CONFIG_TOKEN: "{{ .TOKEN }}"
  dataFrom:
    - sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault
      extract:
        key: forgejo/runner-init
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
