---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flannel
  namespace: kube-flannel
spec:
  interval: 1m0s
  url: https://flannel-io.github.io/flannel/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flannel
  namespace: kube-flannel
spec:
  values:
    podCidr: 10.72.0.0/16
  chart:
    spec:
      chart: flannel
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: flannel
      version: v0.28.5
  interval: 1m0s
