apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: forgejo
    repo: oci://code.forgejo.org/forgejo-helm
    releaseName: forgejo
    version: "17.1.5"
    namespace: forgejo
    valuesInline:
      httpRoute:
        enabled: true
        parentRefs: [{name: "gateway-public", namespace: "kgateway-system"}]
        hostnames: ["code.ramona.fun"]
        matches:
          # this is to allow for long package uploads/downloads
          timeouts:
            backendRequest: "1800s"
            request: "1800s"
      tcpRoute:
        enabled: true
        parentRefs: [{name: "ssh", group: "gateway.networking.k8s.io", kind: "ListenerSet"}]
        port: 22
      persistence:
        accessModes: ["ReadWriteMany"]
        storageClass: longhorn
        size: 25Gi
      gitea:
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        oauth:
          - name: "authentik"
            provider: 'openidConnect'
            existingSecret: forgejo-oauth
            autoDiscoverUrl: "https://account.ramona.fun/application/o/forgejo/.well-known/openid-configuration"
            scopes: 'email profile forgejo'
            requiredClaimName: 'forgejo'
            groupClaimName: 'forgejo'
            adminGroup: 'admin'
            restrictedGroup: 'restricted'
        config:
          APP_NAME: "ramona's code"
          log:
            LEVEL: "debug"
          oauth2:
            JWT_SIGNING_ALGORITHM: RS256
          service:
            DISABLE_REGISTRATION: "true"
          oauth2_client:
            ENABLE_AUTO_REGISTRATION: "true"

        additionalConfigSources:
          - secret:
              secretName: forgejo-db

resources:
  - database.yaml
  - tcp-listener-set.yaml
  - oauth.yaml
