apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: vault
  name: vault-server
spec:
  issuerRef:
    name: vault-self-issuer
    kind: ClusterIssuer
  secretName: vault-server
  commonName: vault.internal.ramona.fun
  dnsNames:
    - vault.internal.ramona.fun
    - vault.vault.svc.cluster.local
