apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: egress-proxies
spec:
  type: egress
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: kgateway-system
  annotations:
    tailscale.com/tailnet-fqdn: "hallewell.ibis-draconis.ts.net"
    tailscale.com/proxy-group: "egress-proxies"
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - port: 8096
      protocol: TCP
      name: http
