"""
This type stub file was generated by pyright.
"""

from zigpy.config import CONFIG_SCHEMA

"""Default configuration values."""
CONF_DECONZ_CONFIG = ...
CONF_MAX_CONCURRENT_REQUESTS_DEFAULT = ...
CONFIG_SCHEMA = ...
