"""
This type stub file was generated by pyright.
"""

"""deCONZ serial protocol API."""
LOGGER = ...
def restart_forever(func, *, restart_delay=...): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Coroutine[Any, Any, NoReturn]]:
    ...

