[package]
name = "ras"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
axum-tracing-opentelemetry = "0.18.0"
opentelemetry = "0.22.0"
opentelemetry-otlp = "0.15.0"
opentelemetry_sdk = { version = "0.22.1", features = ["tokio", "rt-tokio"] }
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
tracing-opentelemetry = "0.23.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
ratlib = { path = "../../libs/rust/ratlib/" }
