[package]
name = "ras"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
axum-tracing-opentelemetry = "0.18.0"
opentelemetry = "0.22.0"
opentelemetry-otlp = "0.15.0"
opentelemetry_sdk = { version = "0.22.1", features = ["tokio", "rt-tokio"] }
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
tracing-opentelemetry = "0.23.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
ratlib = { path = "../../libs/rust/ratlib/" }
serde = { version = "1.0.197", features = ["derive"] }
chrono = { version = "0.4.37", features = ["serde"] }
chrono-tz = { version = "0.9", features = ["serde"] }
thiserror = "1.0.58"
serde_json = "1.0.115"
tokio-postgres = "0.7.10"
