apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: service-ingress
spec:
  type: ingress
  replicas: 2
  tags: 
    - "tag:k8s-service"
    - "tag:k8s"
  hostnamePrefix: 'darkmore-proxy-'
