apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-proxy
spec:
  issuerRef:
    name: vault-self-issuer
    kind: ClusterIssuer
  secretName: auth-proxy-certs
  commonName: auth-proxy.ramona.fun
  dnsNames:
    - ras.ramona.fun
