apiVersion: v1
kind: Service
metadata:
  name: auth-proxy
spec:
  selector:
    app: auth-proxy
  type: ClusterIP
  ports:
  - name: auth-proxy
    protocol: TCP
    port: 3000
    targetPort: 3000
  - name: mtls
    port: 3001
    targetPort: 3001
