apiVersion: gateway.kgateway.dev/v1alpha1
kind: ListenerPolicy
metadata:
  name: gateway-public
  namespace: kgateway-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway-public
  default: 
    proxyProtocol: {}
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: gateway-public
  namespace: kgateway-system
spec:
  kube:
    deployment:
      replicas: 2
    service:
      type: LoadBalancer
      extraAnnotations:
        "load-balancer.hetzner.cloud/name": "gateway-public"
        "load-balancer.hetzner.cloud/location": "nbg1"
        "load-balancer.hetzner.cloud/uses-proxyprotocol": "true"
        "load-balancer.hetzner.cloud/private-subnet-ip-range": "10.1.0.0/24"
        "load-balancer.hetzner.cloud/disable-private-ingress": "true"
        "load-balancer.hetzner.cloud/use-private-ip": "true"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-public
  namespace: kgateway-system
  annotations: 
    cert-manager.io/cluster-issuer: cert-manager-webhook-dnsimple-production
spec: 
  gatewayClassName: 'kgateway'
  infrastructure:
    parametersRef:
      group: gateway.kgateway.dev
      kind: GatewayParameters
      name: gateway-public

  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      port: 443
      protocol: HTTPS
      hostname: '*.ramona.fun'
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: wildcard-ramona-fun
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: ListenerPolicy
metadata:
  name: gateway-tailscale
  namespace: kgateway-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway-tailscale
  default: 
    proxyProtocol: {}
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: gateway-tailscale
  namespace: kgateway-system
spec:
  kube:
    deployment:
      replicas: 2
    service:
      type: LoadBalancer
      loadBalancerClass: 'tailscale'
      extraAnnotations:
        "tailscale.com/proxy-group": "service-ingress"
        "tailscale.com/tags": "tag:k8s,tag:k8s-service"
        "tailscale.com/hostname": "gateway"
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-tailscale
  namespace: kgateway-system
  annotations: 
    # TODO https://github.com/kubernetes-sigs/external-dns/issues/6507
    "external-dns.alpha.kubernetes.io/target": "100.119.189.53"
    cert-manager.io/cluster-issuer: cert-manager-webhook-dnsimple-production
spec: 
  gatewayClassName: 'kgateway'
  infrastructure:
    parametersRef:
      group: gateway.kgateway.dev
      kind: GatewayParameters
      name: gateway-tailscale

  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      port: 443
      protocol: HTTPS
      hostname: '*.infrastructure.ramona.fun'
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: wildcard-infrastructure-ramona-fun
