apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: jellyfin
  namespace: kgateway-system
spec:
  type: Static
  static:
    hosts:
      - host: jellyfin
        port: 8096
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
  namespace: kgateway-system
spec:
  parentRefs:
  - name: gateway-public
    namespace: kgateway-system
  hostnames:
    - jellyfin-test.ramona.fun
  rules:
    - backendRefs:
      - name: jellyfin
        kind: Backend
        group: gateway.kgateway.dev
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: kgateway-system
  annotations:
    tailscale.com/tailnet-fqdn: "hallewell.ibis-draconis.ts.net"
    tailscale.com/proxy-group: "egress-proxies"
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - port: 8096
      protocol: TCP
      name: http
