when:
  - event: cron
    cron: flake-update
steps:
  - name: check
    image: code.ramona.fun/ramona/monorepo/ci:1787074275
    commands:
      - ./.woodpecker/scripts/flake-update.bash
    environment:
      ATTIC_TOKEN:
        from_secret: "attic_token"
      SSH_KEY:
        from_secret: "ssh_key"
      CACHE_ACCESS_KEY_ID:
        from_secret: "hetzner_access_key_id"
      CACHE_ACCESS_KEY_SECRET:
        from_secret: "hetzner_secret_access_key"
      GITHUB_TOKEN:
        from_secret: "github_token"
      FORGEJO_TOKEN:
        from_secret: "forgejo_token"
