# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ras
  labels:
    app: ras
spec:
  selector:
    matchLabels:
      app: ras
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: ras
      labels:
        app: ras
    spec:
      imagePullSecrets:
        - name: forgejo-container-credentials
      containers:
      - name: ras
        image: code.ramona.fun/ramona/monorepo/ras:1786960918.194204
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 25m
            memory: 15Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            port: 3000
            path: /health
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        envFrom:
            - secretRef:
                name: ras
        ports:
        - containerPort: 3000
          name: ras
      restartPolicy: Always
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ras
spec:
  refreshInterval: 1m
  target:
    name: ras
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: 'postgres://{{ .username }}:{{ .password }}@cloudnative-pg-database-cluster-pooler-rw.cloudnative-pg-database/ras'
  dataFrom:
    - sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault
      extract:
        key: postgres/ras
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-container-credentials
spec:
  target:
    name: forgejo-container-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ index . "docker-config-json" | toString }}'
  dataFrom:
    - sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault
      extract:
        key: forgejo-container-registry-config
