kind: ConfigMap
apiVersion: v1
metadata:
  name: ras-datasource
  namespace: grafana
  labels:
    grafana_datasource: "1"
data:
  infinity.yaml: |-
    apiVersion: 1

    datasources:
      - name: Infinity
        type: yesoreyeram-infinity-datasource


