apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
spec:
  apiServer: 
    extraArgs:
      - { name: "logging-format", value: "json" }
    resources:
      requests:
        memory: 512Mi
  apiVersion: kubeadm.k8s.io/v1beta4
  caCertificateValidityPeriod: 87600h0m0s
  certificateValidityPeriod: 8760h0m0s
  certificatesDir: /etc/kubernetes/pki
  clusterName: kubernetes
  controlPlaneEndpoint: 127.0.0.1:6444
  controllerManager:
    extraArgs:
      - { name: "bind-address", value: "0.0.0.0" }
      - { name: "logging-format", value: "json" }
  dns: {}
  encryptionAlgorithm: RSA-2048
  imageRepository: registry.k8s.io
  kind: ClusterConfiguration
  kubernetesVersion: v1.36.2
  networking:
    dnsDomain: cluster.local
    podSubnet: 10.2.0.0/16
    serviceSubnet: 10.16.0.0/12
  proxy: {}
  scheduler:
    extraArgs:
      - { name: "bind-address", value: "0.0.0.0" }
      - { name: "logging-format", value: "json" }
  etcd:
    local:
      dataDir: /var/lib/etcd
      extraArgs:
        - { name: "listen-metrics-urls", value: "http://0.0.0.0:2381" }
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
spec:
  metricsBindAddress: 0.0.0.0:10249
  logging:
    format: "json"
---
apiVersion: kubelet.config.k8s.io/v1alpha1
kind: KubeletConfiguration
spec:
  metricsBindAddress: 0.0.0.0:10249
  logging:
    format: "json"
  failSwapOn: false
  memorySwap:
    swapBehaviour: LimitedSwap
