on: 
  pull_request: ~
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Setup ssh credentials
        run: ./.github/scripts/credentials.sh
        env:
          LIX_REPO_TOKEN: "${{ secrets.LIX_REPO_TOKEN }}"

      - name: put the SSH key in a file
        run: echo "${{ secrets.SSH_KEY }}" > id_ed25519

      - name: build all machines
        id: build-all
        run: ./.github/scripts/build.sh "${{ steps.extract_branch.outputs.branch }}"
        env:
          B2_APPLICATION_KEY_ID: "${{ secrets.B2_APPLICATION_KEY_ID }}"
          B2_APPLICATION_KEY: "${{ secrets.B2_APPLICATION_KEY }}"

      - name: Find Comment
        # dependabot is excluded, because dependabot PRs don't have acceess to secrets
        if: github.ref != 'refs/heads/main' && github.actor != 'dependabot[bot]'
        uses: peter-evans/find-comment@v4
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'ramonacat'
          body-includes: Build results
          token: "${{ secrets.PAT }}"

      - uses: actions/upload-artifact@v7
        with:
          name: container-images
          path: result/containers/

      - uses: actions/upload-artifact@v7
        with:
          name: npm-packages
          path: result/npm-packages/

      - name: Create or update comment
        if: github.ref != 'refs/heads/main' && github.actor != 'dependabot[bot]'
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.build-all.outputs.READABLE_OUTPUT }}
          edit-mode: replace
          token: "${{ secrets.PAT }}"
    
  upload-containers:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs: ["build"]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: download the container images
        uses: actions/download-artifact@v8
        with:
          name: container-images
          path: containers

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: upload to the container registry
        run: ./.github/scripts/upload-containers.bash

  npm-publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs: ["build"]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: download the container images
        uses: actions/download-artifact@v8
        with:
          name: npm-packages
          path: npm-packages

      - name: upload to the npm registry
        run: ./.github/scripts/upload-npm-packages.bash
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
