name: Flake Checks
on: 
  pull_request: ~
  push:
    branches:
      - 'main'

jobs:
  flake-check:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: nix flake check
        run: nix flake check
