name: Update Fleet with new settings
on: 
  pull_request: ~
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Run fleet gitops
        run: nix shell nixpkgs#fleetctl --command ./.github/scripts/fleet.bash "${{ steps.extract_branch.outputs.branch }}"
        env:
          FLEET_URL: "https://fleet.services.ramona.fun/"
          FLEET_API_TOKEN: "${{ secrets.FLEET_API_TOKEN }}"
          FLEET_GLOBAL_ENROLL_SECRET: "${{ secrets.FLEET_GLOBAL_ENROLL_SECRET }}"
