name: update flux
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '5 3 * * *' # daily at 03:05

permissions:
  pull-requests: write
  contents: write

jobs:
  flux-update: |
    export BRANCH_NAME=update_flux_$(date +%Y%m%d%H%M%S)

    git config user.name "github-actions[bot]"
    git config user.email "<>"

    git checkout -b $BRANCH_NAME

    nix develop --command 'flux install --export > ./clusters/darkmore/flux-system/gotk-components.yaml'

    git diff-index --quiet --cached HEAD --
    if [[ $? -ne 0 ]]; then
      git commit -a -m"update flux"
      git push origin $BRANCH_NAME

      pr_url="$(gh pr create --title 'Update flux' --body 'Update flux')"
      gh pr merge --auto -r "$pr_url"
    fi
