name: terraform
on: 
  pull_request_target: ~
  push:
    branches:
      - 'main'

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 50

      - name: put the SSH key in a file
        run: mkdir -p $HOME/.ssh && echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_ed25519 && ssh-keygen -y -f ~/.ssh/id_ed25519 > ~/.ssh/id_ed25519.pub

      - name: tflint
        run: nix develop --command sh -c "cd terraform && tflint --init && tflint"

      - name: terraform init
        run: nix develop --command sh -c "cd terraform && terraform init -input=false"

      - name: terraform validate
        if: github.head_ref != 'refs/heads/main'
        run: nix develop --command sh -c "cd terraform && terraform validate"

      - name: terraform plan
        if: github.head_ref != 'refs/heads/main'
        id: terraform-plan
        run: nix develop --command sh -c "./.github/scripts/terraform-plan.sh"

      - name: Find Comment
        # dependabot is excluded, because dependabot PRs don't have acceess to secrets
        if: github.head_ref != 'refs/heads/main' && github.actor != 'dependabot[bot]'
        uses: peter-evans/find-comment@v4
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'ramonacat'
          body-includes: terraform plan
          token: "${{ secrets.PAT }}"

      - name: Create or update comment
        if: github.head_ref != 'refs/heads/main' && github.actor != 'dependabot[bot]'
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "terraform plan: <br/>\n${{ steps.terraform-plan.outputs.READABLE_OUTPUT }}"
          edit-mode: replace
          token: "${{ secrets.PAT }}"

      # apparently github creates a made up merge commit and runs the actions in pull requests on that, so it's also needed on the feature branch
      - name: find merge parent
        id: find_merge_parent
        run: ./.github/scripts/find-merge-parent.sh
      
      - name: upload the plan
        if: github.head_ref != 'refs/heads/main'
        run: "scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i $HOME/.ssh/id_ed25519 terraform/plan.tfplan.age root@hallewell.ibis-draconis.ts.net:/var/ci/terraform-plans/${{ steps.find_merge_parent.outputs.parent }}.tfplan.age"

      - name: download plan
        if: github.head_ref == 'refs/heads/main'
        run: "scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i $HOME/.ssh/id_ed25519 root@hallewell.ibis-draconis.ts.net:/var/ci/terraform-plans/${{ steps.find_merge_parent.outputs.parent }}.tfplan.age terraform/plan.tfplan.age" 

      - name: terraform apply
        if: github.head_ref == 'refs/heads/main'
        run: nix develop --command sh -c "cd terraform && age -d -i ~/.ssh/id_ed25519 plan.tfplan.age > plan.tfplan && terraform apply -input=false plan.tfplan && rm plan.tfplan"
